packages/create_ap/PKGBUILD
This completes https://github.com/BlackArch/blackarch/commit/7d63daa822ee7ef0db83d20eb27f0a8332aca7bc.
=> change create-ap to create_ap using

packages/blackarch-mirrorlist/PKGBUILD, packages/blackarch-mirrorlist/blackarch-mirrorlist
Includes PKGBUILD and blackarch-mirrorlist
=> Created BlackArch mirrorlist package

packages/snort/PKGBUILD, packages/tor-browser-en/PKGBUILD
Resolves issue #928  2015-07-30
=> snort version bump 2.9.7.5

packages/v3n0m/PKGBUILD
Updated Search_Ignore and update Metasploit-Vulns
=> Updated Search_Ignore and update Metasploit-Vulns

packages/drozer/PKGBUILD, packages/gophish/PKGBUILD
Damn nice app, this comes in handy with mobile app pentesting a lot.
=> Added drozer for Android App hacking

packages/v3n0m/PKGBUILD
Added the overdue change to Python3.5s usage of Asyncio, vastly improves speed
Now searches blocks of pages at once instead of just 1 page per request
Discovered Asyncio with futures using request.get no longer suppresses natively the 
socket errors or any other errors, so added a ignoreGET wrapper to ignore this bug :)
Started working on a new Asyncio based TCP Scanner which will at some point form the basics of the "Honeypot" detection function.
=> Asyncio Search method added

packages/recon-ng/PKGBUILD
version bump from recon-ng-4.7.3 to recon-ng-4.7.4
=> recon-ng version bump

packages/crackmapexec/PKGBUILD
take a look at issue https://github.com/BlackArch/blackarch/issues/1076 for more informations
=> update 'crackmapexec' package (resolves #1076)

packages/blackmate/PKGBUILD
And update to the the version to the 0.3, fixing the generation, 21 categories displayed with new icons
=> Remove useless depends for use this tool

.gitignore, scripts/images/docker/Dockerfile, scripts/images/docker/README.md, scripts/images/docker/build-helper.sh, scripts/images/docker/build-pacman.conf, scripts/images/docker/build.sh
Hello,
this is only a first rough draft of a Docker image build infrastructure for BlackArch. Please read the README, play around and let me know what I can change. I do not expect this to get merged in its current form, yet I hope to get it incorporated at some later point. I tried to adhere to the style of `strap.sh`.
Cheers,
heichblatt
=> docker: first rough draft

packages/dripcap/PKGBUILD
=> Added dripcap

packages/proctal/PKGBUILD, packages/yuck/PKGBUILD
=> proctal package

packages/empire/PKGBUILD, packages/empire/empire.install, packages/python2-iptools/LICENSE, packages/python2-iptools/PKGBUILD, packages/python2-pydispatcher/PKGBUILD
Yet another tool, requested in #1066.
I hope this time I got the style- and install-aspects right ;)
=> new tool: Empire

mirror/mirror.lst
=> Added New Mirror

packages/analyzepesig/PKGBUILD
This will handle BlackArch/blackarch#1551
=> Update analyzepesigs group information

packages/bloodhound/singlearch.patch
Crap, I totally missed adding that one, sorry.
=> missing .patch file for bloodhound

packages/faraday/PKGBUILD
added deps: vte3, python2-gobject, curl
=> fix 'faraday' missing dependencies

packages/airgraph-ng/PKGBUILD
Create a directory as @aancw recommends in BlackArch/blackarch#1547
=> Airgraph-ng create directory

packages/insanity/PKGBUILD
This fixes BlackArch/blackarch#1549
=> Insanity - Set python2.7 as fix version in settings.py

packages/python-gdbgui/PKGBUILD, packages/python-gdbgui/python-gdbgui.install
Adding gdbgui because of #1643
=> Adding new tool gdbgui  

packages/blackmate/PKGBUILD
=> blackmate Update 0.43

packages/recon-ng/PKGBUILD
=> upgrade 'recon-ng' to version 4.9.2

packages/eternal_scanner/PKGBUILD
https://github.com/peterpt/eternal_scanner
https://github.com/BlackArch/blackarch/issues/1737
This is my first contribution. Please let me know if I should stick with any format for my pulls.
I intend to send further PKG files.
=> [tool request] PKGBUILD for eternal_scanner tool

packages/sploitctl/PKGBUILD
This pull is related to https://github.com/BlackArch/sploitctl/pull/8 in sploitctl.
I'm not sure about `pkgver`, so a review would be interesting.
=> [update] sploitctl has now a bash-completions.

packages/massbleed/PKGBUILD, packages/massbleed/massbleed.install
Hey guys I notice the tool sn1per in the blackarch repos needs this tool as well. since is not in the repo nor in arch repos here I created a simple install.
keep it up.
=> Added new tool massbleed

packages/whichcdn/PKGBUILD
a very simple fix. have a nice day.
=> fixed typo in package description of whichcdn

packages/rtfm/PKGBUILD
https://github.com/BlackArch/blackarch/issues/1697
=> [tool request] adding rtfm #1697

packages/raven/PKGBUILD
review of /opt or /usr/share according to my previous PR is necessary.
=> [tool request] adding raven: #1759.

packages/nfsshell/PKGBUILD
Again, a check would be nice! :P
=> [fix] nfsshell fix part of #1259.

packages/rspet/PKGBUILD
It would be interesting a check.
=> [fix] rspet error part of #1259.

packages/trusttrees/PKGBUILD
As requested on https://github.com/BlackArch/blackarch/issues/1686 by @vdun.
=> [tool request] adding TrustTrees.

packages/graBing/PKGBUILD
=> Adding Tool: graBing

packages/pacaur/PKGBUILD
This PKGBUILD file was extracted from AUR
#1286 
Adding `pacaur`.
Attention: this PKGBUILD was extracted from AUR.
=> [tool request] pacaur.

packages/brosec/PKGBUILD
Added directory and PKGBUILD for brosec - https://github.com/gabemarshall/Brosec
=> Added brosec

packages/gosint/PKGBUILD
Fixed missing dependencies and installation of config file
=> Fixed gOSINT PKGBUILD

packages/dislocker/PKGBUILD
Tracking https://github.com/BlackArch/blackarch/issues/1889
=> dislocker: update new version and fixing source.

packages/pwnloris/PKGBUILD
resolve BlackArch/blackarch#1893
=> Update pwnloris repository URL

packages/searchsploit/PKGBUILD, packages/searchsploit/searchsploit.install
open the possibility to add more packages, such as TheFatRat.
Signed-off-by: Pedro Freitas <pedrosffreitas@gmail.com>
=> searchsploit: fix findsploit dependency and

packages/networkminer/PKGBUILD
https://www.netresec.com/?page=NetworkMiner
=> networkminer: adding Network Miner.

packages/kekeo/PKGBUILD
https://github.com/gentilkiwi/kekeo/archive/... does not include binaries
https://github.com/gentilkiwi/kekeo/releases/download/.../kekeo.zip does
=> Updated kekeo: added pkgver() and updated URLs

packages/gdbgui/PKGBUILD, packages/gdbgui/setup.py.patch, packages/python-flask-compress/PKGBUILD
- Add new package python-flask-compress as dependency
- update patch file
- remove tests directory to avoid file conflicts
=> Fix gdbgui

packages/instashell/PKGBUILD
This tool can help to test Instagram account for password security.
=> Added new tool: instashell

packages/ivre/PKGBUILD
Most dependencies are actually optional and are now treated as such. New optional dependencies have also been added.
=> IVRE: switch to Python 3

packages/evilginx/PKGBUILD
=> Bump to evilginx 2

packages/spookflare/PKGBUILD
This tool can help to avoid AV and make creating payloads easier.
=> Added new tool: spookflare

packages/firstorder/PKGBUILD
A traffic analyzer to evade Empire's communication from Anomaly-Based IDS.
=> Added new tool: firstorder

packages/merlin-server/PKGBUILD
Merlin is a cross-platform post-exploitation HTTP/2 Command & Control server and agent written in golang.
=> Added new tool: merlin-server

packages/onetwopunch/PKGBUILD
Use unicornscan to quickly scan all open ports, and then pass the open ports to nmap for detailed scans.
=> Added new tool: onetwopunch

packages/sigthief/PKGBUILD
Stealing Signatures and Making One Invalid Signature at a Time.
=> Added new tool: sigthief

.travis.yml, run-tests.sh
This uses [pkgcheck](https://github.com/FFY00/pkgcheck).
=> Add simple check for PKGBUILDs

packages/simplyemail/PKGBUILD
=> simplyemail: add necesary dependences

packages/python-uncompyle6/PKGBUILD
A Python cross-version decompiler.
=> Added new tool: python-uncompyle6

packages/stacoan/PKGBUILD
=> Added stacoan tool

packages/python-names/PKGBUILD, packages/thefatrat/PKGBUILD, packages/thefatrat/thefatrat.install
As soon as my PR will be merge, i will correct this to Screetsec repo.
=> Added new tool: TheFatRat

packages/lazydroid/PKGBUILD
=> LazyDroid: add tool

packages/ba-testpkg/PKGBUILD
=> Removed lines 21 and 22

packages/python2-pdfkit/PKGBUILD
see https://pypi.org/project/pdfkit/
=> add missing dependency

packages/mobsf/PKGBUILD, packages/mobsf/mobsf.install
this is a work in progress, help wanted
- mobsf was in a very old version (lot of changes between `489.712e800` and `775.8fcebdf`)
- I updated dependencies but we still need proper packages for
=> [WIP] updating mobsf

packages/weevely/PKGBUILD
fix https://github.com/epinna/weevely3/issues/98
=> weevely - change the script wrapper

packages/wirouter-keyrec/PKGBUILD
less promotional and less verbose description
=> wirouter-keyrec: pkgdesc change

packages/enum4linux/PKGBUILD
=> missing dependencies

packages/dvcs-ripper/PKGBUILD
package the whole tool https://github.com/kost/dvcs-ripper
=> dvcs-ripper: add missing scripts and deps

packages/aws-extender-cli/PKGBUILD
I tested it works perfectly. `aws-extender-cli -b xxxxxx -s S3`
=> add aws-extender-cli

packages/ivre/PKGBUILD
This will create the following packages:
- ivre
- ivre-web
- ivre-docs
- python-ivre
- python2-ivre
=> Split ivre into subpackages, add python2 support, sync with AUR packages

packages/python-plaso/PKGBUILD
This PR is to be merged.
Old PR und discussions under PR https://github.com/BlackArch/blackarch/pull/2267
=> python-plaso: new tool

packages/airgeddon/PKGBUILD
airgeddon package modified to fix some new dependencies
=> airgeddon package modified to fix some new dependencies

packages/theharvester/PKGBUILD
python-yaml is needed, not python-pyaml. python-retrying is also needed.
=> theharvester: Correct dependencies

packages/wascan/PKGBUILD
=> wascan: better exec file

packages/python-exifread/PKGBUILD
=> [WIP] python-exifread

packages/stegoveritas/PKGBUILD
=> [WIP] stegoveritas

PKGBUILD, packages/littlebrother/PKGBUILD
Hi there!
I added the PKGBUILD for the tool LittleBrother, an OSINT tool to find informations on French, Belgian and Switzerland people.
Also another one: QRLJacker to create fake phishing QRCodes and stuff like that.
Feel free to edit and tell me the changes so I can pull request better next time!
Cheers!
=> Added LittleBrother & QRLJacker

packages/linkfinder/PKGBUILD
Hi there! I created a PKGBUILD for LinkFinder.
It's a python script that finds endpoints in JavaScript files.
Here is a link explaining what and how it does it:
[LINK](https://gerbenjavado.com/discovering-hidden-content-using-linkfinder/)
Cheers!
=> Added LinkFinder PKGBUILD

packages/skiptracer/PKGBUILD
Hi there!
I created the Skiptracer OSINT tool PKGBUILD.
Cheers!
=> Added Skiptracer PKGBUILD

packages/demiguise/PKGBUILD
Hi there!
I created the Demiguise PKGBUILD.
**Description**
*The aim of this project is to generate .html files that contain an encrypted HTA file. The idea is that when your target visits the page, the key is fetched and the HTA is decrypted dynamically within the browser and pushed directly to the user. This is an evasion technique to get round content / file-type inspection implemented by some security-appliances. This tool is not designed to create awesome HTA content. There are many other tools/techniques that can help you with that. What it might help you with is getting your HTA into an environment in the first place, and (if you use environmental keying) to avoid it being sandboxed.*
Cheers!
=> Added Demiguise PKGBUILD

packages/vulmap/PKGBUILD
Hi there!
I added the Vulmap PKGBUILD
**Description**
*Vulmap is an open source online local vulnerability scanner project. It consists of online local vulnerability scanning programs for Windows and Linux operating systems. These scripts can be used for defensive and offensive purposes. It is possible to make vulnerability assessments using these scripts. Also they can be used for privilege escalation by pentesters/red teamers.*
*Vulmap can be used to, scan vulnerabilities on localhost, see related exploits and download them. Scripts basically, scan localhost to gather installed software information and ask vulmon.com api if there are any vulnerabilies and exploits related with installed software. If vulnerabilities exist, Vulmap give CVE ID, risk score, vulnerability's detail link, if …
=> Added Vulmap PKGBUILD

packages/wesng/PKGBUILD
Hi there!
I created the PKGBUILD for Windows Exploit Suggester Next Generation
**Description**
*WES-NG is a tool based on the output of Windows' systeminfo utility which provides the list of vulnerabilities the OS is vulnerable to, including any exploits for these vulnerabilities. Every Windows OS between Windows XP and Windows 10, including their Windows Server counterparts, is supported.*
Cheers!
=> Added Windows Exploit Suggester Next Generation PKGBUILD

lists/to-release
Hi there!
Added some packages (in PRs) to the to-release file.
Cheers!
=> to-release: add packages

lists/to-release, packages/finalrecon/PKGBUILD
=> finalrecon: initial commit

packages/polyswarm-api/PKGBUILD
=> polyswarm-api: fix download

packages/hashcatch/PKGBUILD
Fix PKGBUILD according to the latest release of hashcatch's file organisation
=> Update PKGBUILD of hashcatch

packages/hashcatch/PKGBUILD
Fixed major logic bug in the latest release
=> Fix major bug

packages/lyricpass/PKGBUILD
=> lyricpass : new version

packages/theharvester/PKGBUILD
- add missing dependency #2473
- remove old dependencies
=> theHarvester: fix dependencies

packages/neo4j-community/PKGBUILD
shortly after my last commit, I realized that update 3.5.14 was available. Note - FP's with pkgcheck again
=> update to 3.5.14

packages/powersploit/PKGBUILD
went down a multi-day rabbit hole because powersploit was not on the 'dev' branch :P
Also updated the source url
=> update powersploit pkgbuild

packages/stegcracker/PKGBUILD
Stegcracker- A tool that brute forces the password for Steghide-a steganography tool,using wordlists
=> added stegcracker package

.gitignore, lists/to-release, packages/perl-encoding-ber/PKGBUILD, packages/rdp-sec-check/PKGBUILD
=> add rdp-sec-check

lists/to-release, packages/jwt_tool/PKGBUILD
=> jwt_tool: new tool

packages/chisel/PKGBUILD
=> chisel: fix version display

packages/gcrypt/PKGBUILD
=> gcrypt: fix PKGBUILD

packages/retire/PKGBUILD
=> retirejs: new tool

packages/uhoh365/PKGBUILD
This PR adds PKGBUILD for https://github.com/Raikia/UhOh365
=> UhOh365: Initial commit

packages/spraykatz/PKGBUILD
This PR adds https://github.com/aas-n/spraykatz to the package list and fixes #2626
=> Spraykatz: Initial commit

lists/to-release, packages/windapsearch/PKGBUILD
=> Windapsearch

lists/to-release, packages/sprayingtoolkit/PKGBUILD, packages/sprayingtoolkit/sprayingtoolkit.install
This PR adds all the scripts present in [SprayingToolkit](https://github.com/byt3bl33d3r/SprayingToolkit)
=> SprayingToolkit: Initial Commit

lists/to-release, packages/nosqli-user-pass-enum/PKGBUILD
This PR adds [nosqli-user-pass-enum](https://github.com/an0nlk/Nosql-MongoDB-injection-username-password-enumeration) to the tools arsenal.
=> nosqli-user-pass-enum: Initial commit

packages/dnscobra/PKGBUILD
Initial commit of the [dnscobra](https://github.com/dmitescu/dnscobra/) package
=> dnscobra: initial commit

packages/rekall/PKGBUILD
https://wiki.archlinux.org/index.php/PKGBUILD#license
=> rekall: do not copy license for GPL

packages/snowman/PKGBUILD
tested with ba-dev :heavy_check_mark:
=> snowman: pkgver bump

packages/pwncat/PKGBUILD
> pwncat is a sophisticated bind and reverse shell handler with many features as well as a drop-in replacement or compatible complement to netcat, ncat or socat.
* https://github.com/cytopia/pwncat
* http://pwncat.org/
=> pwncat: initial commit

docs/HOWTO-DEV.md, lists/to-release, packages/cpyrit-cuda/PKGBUILD, packages/cpyrit-cuda/fix-broken-join.patch, packages/cpyrit-cuda/scapy-2.3.2.patch, packages/websploit/PKGBUILD, packages/windowsspyblocker/PKGBUILD, packages/x3270/PKGBUILD, packages/yate-bts/PKGBUILD, packages/zxing/PKGBUILD
Updated a few packages with their respective new upstream URLs. One thing though, websploit now requires the python-requests package which is satisfied on my Arch Linux system but I couldn't find it within blackarch. Should I add it to the packages?
One more question, where did the Wireshark package go? It isn't available in this repository anymore :/
Cheers,
Felix Golatofski
=> Updated: packages

lists/to-release, packages/cafebabe/PKGBUILD
=> add cafebabe

lists/to-release, packages/metasploit-git/PKGBUILD
- Adding metasploit git (dev) PKGBUILD.
=> pkgbuild: metasploit: git version.

lists/to-release, packages/mobsf/PKGBUILD
Ref : https://github.com/MobSF/Mobile-Security-Framework-MobSF/tree/master/scripts
=> mobsf: Cleanup additional files

lists/to-release, packages/vipermonkey/PKGBUILD
This PR adds [ViperMonkey](https://github.com/decalage2/ViperMonkey/) and fixes #2572
=> Add vipermonkey

packages/vipermonkey/setup.py.patch, packages/vipermonkey/vipermonkey.install
Forgot this in #2874  sorry :(
=> vipermonkey: add missing install and patch files

lists/to-release, packages/cmsscan/PKGBUILD, packages/cmsscanner/PKGBUILD
=> cmsscan: add tool

lists/to-release, packages/python-boofuzz/PKGBUILD
This PR adds python-boofuzz and fixes #2483
=> python-boofuzz: initial commit.

lists/to-release, packages/gitdorker/PKGBUILD
This PR adds PKGBUILD for [GitDorker](https://github.com/obheda12/GitDorker).
=> gitdorker: initial commit.

lists/to-release, packages/python-mmh3/PKGBUILD
replace & close  #2909, #2904, #2888
dep required for #2888
=> add python-mmh3

lists/to-release, packages/python-ccrawl/PKGBUILD
=> add python-ccrawl

lists/to-release, packages/favfreak/PKGBUILD
closes #2888
replace & close #2902
=> add favfreak

lists/to-release, packages/stringsifter/PKGBUILD
=> StringSifter #2829

lists/to-release, packages/stringsifter/PKGBUILD
=> Stringsifter fix

lists/to-release, packages/stringsifter/PKGBUILD
- fixed uptream https://github.com/fireeye/stringsifter/pull/15
=> remvoe workaround

lists/python2-tools, lists/to-release, packages/sireprat/PKGBUILD
Waiting for the author to add a LICENSE. [Issue](https://github.com/SafeBreach-Labs/SirepRAT/issues/11) opened for this on the repo.
_Text shamelessly stolen from @noraj's issue in favfreak :)_
=> add sireprat.

lists/to-release, packages/shellerator/PKGBUILD
=> Shellerator #2923

lists/to-release, packages/crackmapexec/PKGBUILD
=> crackmapexec pkgrel=3; new pipx install

lists/to-release, packages/enum4linux-ng/PKGBUILD
close https://github.com/cddmp/enum4linux-ng/issues/11
close https://github.com/BlackArch/blackarch/issues/2925
=> add enum4linux-ng

lists/to-release, packages/uberfile/PKGBUILD
close https://github.com/BlackArch/blackarch/issues/2924
waiting for https://github.com/ShutdownRepo/uberfile/pull/2 to be merged and retest
=> uberfile: initial commit.

lists/to-release, packages/shellerator/PKGBUILD
close https://github.com/BlackArch/blackarch/issues/2923
=> shellerator: package with setuptools

lists/to-release, packages/rawsec-cli/PKGBUILD
- fix dependencies after https://github.com/mBouamama/rawsec_cli/commit/8876e76b9bde001c6c10706fb8bfb96fcf205040
- update to last commit (new features)
=> rawsec-cli: update & fix

lists/to-release, packages/python-questionary/PKGBUILD
=> python-questionary; new myjwt dep

lists/to-release, packages/python-sarif-om/PKGBUILD
=> njsscan lib dep

lists/to-release, packages/python-comment-parser/PKGBUILD, packages/threatspec/PKGBUILD
=> Add threatspec + deps

lists/to-release, packages/quark-engine/PKGBUILD
=> quark-engine: version bump and add deps.

scripts/check-mirror.py
=> check-mirror.py: python3 script to check mirrors.

lists/to-release, packages/gostringsr2/PKGBUILD
https://github.com/CarveSystems/gostringsr2
=> Add gostringsr2

lists/to-release, packages/darkdump/PKGBUILD
=> darkdump #3010

lists/to-release, packages/enumerate-iam/PKGBUILD
URL: https://github.com/andresriancho/enumerate-iam/
=> New tool: enumerate-iam

lists/to-release, packages/python-gitignore-parser/PKGBUILD, packages/tell-me-your-secrets/PKGBUILD
https://github.com/valayDave/tell-me-your-secrets
A simple module which finds files with different secrets keys present inside a directory. Secrets derived from 120 different signatures.
=> Add tell-me-your-secrets

lists/to-release, packages/pencode/PKGBUILD
=> pencode fixes #3066

lists/to-release, packages/ffuf-scripts/PKGBUILD
=> ffuf-scripts fixes #3067

lists/to-release, packages/python-jproperties/PKGBUILD, packages/python-luhn/PKGBUILD, packages/whispers/PKGBUILD
https://github.com/Skyscanner/whispers/
Whispers is a static code analysis tool designed for parsing various common data formats in search of hardcoded credentials and dangerous functions. Whispers can run in the CLI or you can integrate it in your CI/CD pipeline.
=> Add whispers

lists/to-release, packages/qsreplace/PKGBUILD
=> qsreplace fixes #3098

lists/to-release, lists/to-release-arm, packages/python-pypsrp/PKGBUILD
```
[builduser@blackarch-arm tmp]$ makepkg -s
==> Making package: python-pypsrp v0.5.0.r5.gc704874-1 (Fri Jun  4 21:00:02 2021)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
-> Cloning pypsrp git repo...
Cloning into bare repository '/tmp/pypsrp'...
remote: Enumerating objects: 1608, done.
remote: Counting objects: 100% (357/357), done.
remote: Compressing objects: 100% (248/248), done.
remote: Total 1608 (delta 239), reused 220 (delta 107), pack-reused 1251
Receiving objects: 100% (1608/1608), 1.49 MiB | 5.49 MiB/s, done.
Resolving deltas: 100% (1177/1177), done.
==> Validating source files with sha512sums...
pypsrp ... Skipped
==> Extracting sources...
-> Creating working copy of pypsrp git repo...
Cloning into 'pypsrp'...
done. …
```
=> python-pypsrp: add aarch64 to arch

lists/to-release, lists/to-release-arm, packages/python-pypsrp/PKGBUILD
This reverts commit a6ffd46f081fd5e6d6faccf6ee15a84553b41603.
=> Revert "python-pypsrp: add aarch64 to arch."

lists/to-release, packages/evil-winrm/PKGBUILD
=> evil-winrm: tmp fix

packages/pyspf/PKGBUILD
when making the python2 of the library it showed error while installing :
``` 
error: failed to commit transaction (conflicting files)
/usr/bin/spfquery.py exists in both 'python-spf' and 'python2-spf'
```
check the package name variables, this a tool dependency between
=> pyspf : initial commit

packages/py3dns/PKGBUILD
=> py3dns : initial commit

packages/rule/PKGBUILD
check the pkgdesc because i don't know exactly what it's doing : /
=> rule : initial commit

packages/nettacker/PKGBUILD
check the setup.py script then check the prepare() function.
=> fix for #3129

lists/to-release, packages/github-dorks/PKGBUILD
=> github-dorks fixes #3160

packages/PKGBUILD
a tool dependency.
i am aware of that the library license is MIT and should be installed, but i am confused where to write the install command
=> puremagic: initial commit

packages/deepce/PKGBUILD
=> deepce: initial commit

packages/bkcrack/PKGBUILD
This PR fixes #3122
totally not sure about this PKGBUILD lol
=> bkcrack: initial commit

packages/hiddeneye-legacy/PKGBUILD, packages/python-kill/PKGBUILD, packages/python-values/PKGBUILD
This PR fixes #2866
note: didn't remove the GPL3 license because the tool needs it : /
=> HiddenEye-Legacy: initial commit

lists/to-release, packages/pwcrack/PKGBUILD, packages/pwcrack/pwcrack.install
=> add pwcrack

packages/xxxpwn-smart/PKGBUILD, packages/xxxpwn/PKGBUILD
=> xxxpwn + xxxpwn_smart : initial commit

packages/intelmq/PKGBUILD
=> intelmq: initial commit

packages/rbkb/PKGBUILD
closes #2485
note : first time with ruby :))
=> rbkb: initial commit

packages/mobsf/PKGBUILD, packages/mobsf/mobsf.install
Some paths changed, quark-engine now needed, Migration will eventually fail because of this i added a message to .install.
=> Update to Mobsf 3.4 

lists/to-release, packages/dftimewolf/PKGBUILD, packages/dftimewolf/dftimewolf.install
=> add dftimewolf

packages/pwncat-caleb/PKGBUILD, packages/python-zdaemon/PKGBUILD, packages/python-zeo/PKGBUILD, packages/python-zodb/PKGBUILD, packages/python-zodbpickle/PKGBUILD, packages/python-zodburi/PKGBUILD
=> pwncat-caleb: initial commit

packages/dependency-check/PKGBUILD
I saw some tool request from 2017 which is still open [#1299](https://github.com/BlackArch/blackarch/issues/1299)
and wanted to contribute.
=> dependency-check:initial commit

packages/gmsadumper/PKGBUILD
=> gmsadumper: initial commit

scripts/gen-desktop-files
=> Add desktop file generator script

packages/fscan/PKGBUILD
closes #3234.
note : this tool is unlicensed
=> fscan: initial commit

lists/to-release, packages/evil-winrm/PKGBUILD
version 3.3
https://github.com/Hackplayers/evil-winrm/blob/master/CHANGELOG.md#33
=> evil-winrm: pkgver update

mirror/mirror.lst
=> add gethosted

mirror/mirror.lst
fix https://github.com/BlackArch/blackarch/issues/3236
=> mirror: add nju

packages/holehe/PKGBUILD
=> holehe: initial commit

packages/lpsc/PKGBUILD
closes #3244
note : i named the binary/pkgname `lpsc`
=> local-php-security-checker/lpsc : initial commit

packages/gcrypt/PKGBUILD
=> gcrypt : update package's source url

packages/rustcat/PKGBUILD
~Corrected pkgver() function~
Install license (MIT)
~Removed pointless custom variable~
=> rustcat: pkgbuild revision

packages/dnscan/PKGBUILD
=> dnscan: initial commit

lists/to-release, packages/jwt-tool/PKGBUILD, packages/jwt-tool/jwt-tool.install
=> jwt-tool: fix #3270

lists/to-release, packages/python-egcd/PKGBUILD, packages/rsactftool/PKGBUILD
=> rsactftool: fix dependencies

packages/log4j-bypass/PKGBUILD, packages/log4j-bypass/PKGBUILD.sh
Hello,
This script tests for log4j vulnerabilities on web URLs and is compatible with BlackArch. Please consider adding it. Thank you!
=> Add log4j-bypass.py

packages/portspoof/PKGBUILD
fix https://github.com/BlackArch/blackarch-site/issues/149
=> portspoof: upstream URL change

lists/to-release, packages/python2-setuptools-scm/PKGBUILD
=> python2-setuptools-scm: add tool after community removal

packages/wapiti/PKGBUILD
- New source for the package (git)
- Updated docs
- Last version directly from the git (3.0.9) while maintaining a clean dependency management, without the need of **pip**
- pkgrel+1 (4)
- Removed obsolete **_pkgname** variable and all refs to it
- Updated dependencies
=> wapiti: PKGBUILD update.

packages/rtl8812au-aircrack-dkms/PKGBUILD, packages/rtl8812au-aircrack-dkms/dkms.conf
=> rtl8812au-aircrack-dkms: initial release

packages/interactsh-client/PKGBUILD
interactsh-client: create package.
=> interactsh-client: create package.

packages/python2-virtualenv/PKGBUILD
=> python2-virtualenv: move makedepends to depends

lists/to-release, packages/firefox-decrypt/PKGBUILD
=> firefox-decrypt: add tool

packages/feroxbuster/PKGBUILD
- added shell completions
- updated docs
=> feroxbuster: added shell completions, updated docs.

packages/mobsf/PKGBUILD, packages/mobsf/mobsf.install
Hi, no change, only migration to 3.5.0 to version 3.5.1
=> mobsf: upgrade from 3.5.0 to 3.5.1

packages/postman/PKGBUILD, packages/postman/postman.desktop
=> postman: initial commit

packages/neo4j-community/PKGBUILD, packages/neo4j-community/bin.patch, packages/neo4j-community/neo4j-sysuser.conf, packages/neo4j-community/neo4j.conf, packages/neo4j-community/neo4j.service
to come with #3347 I upgraded neo4j
I'm not sure if it's perfect but at least it works
=> upgrade to neo4j 4

lists/to-release, packages/spraycharles/PKGBUILD
This PR adds [SprayCharles](https://github.com/Tw1sm/spraycharles/)
=> New tool : Spraycharles

packages/typo3scan/PKGBUILD
=> typo3scan replaces typo-enumerator

packages/v3n0m/PKGBUILD, packages/venom/PKGBUILD
- Refactoring entire structure of code
- Updated docs (finally)
- Now using Poetry for easy installation of dependencies (no more annoying "HOW DO I" issues)
- Removed obsolete code and fixed speed/timing of dorking
- Updated dependencies
- Fix several known bugs from issues and also fix recent CVE's
- ADVISORY: USE PROXIES/VPN [Required], this does not include proxies anymore because of a bug yet unfixed
- Additionally, do not directly attack (autosploit) websites, explicitly disallowed for security
- New banner
- Fix Cloudflare Resolver [Cloudbuster]
- CCTV (WIP) (see dev branch [BugFixes-NEEDSTESTING](https://github.com/v3n0m-Scanner/V3n0M-Scanner/tree/kattstof-BugFixes-NEEDSTESTING))
- SQL Injection Vuln Scanner updated
- Detects all known WAFs
- Fix bug from Toxin 
- Only uses Bing …
=> venom: upgrade to 4.3.3

packages/empire/PKGBUILD
=> empire: add missing dependecies

lists/to-release, packages/eyewitness/PKGBUILD
=> eyewitness: fix execution path and bump version

lists/to-release, packages/dirsearch/PKGBUILD
please review.
pip requirements fix; python-pyparsing vers >= 3.0.4 --
deps update --
=> dirsearch pip requirements fix

packages/emp3r0r/PKGBUILD, packages/massexpconsole/PKGBUILD
copy necessary files from `/usr/share/massexpconsole` to `~/.mec` so mec should be able to find them
=> fix massexpconsole

packages/python-semgrep/PKGBUILD
=> semgrep permission issue

packages/loki-packet/PKGBUILD
avoid conflict with https://archlinux.org/packages/community/x86_64/loki/
=> loki: change pkgname

packages/gf/PKGBUILD
Hi there!
A small pull request for the awesome gf by @tomnomnom.
Cheers!
=> gf: initiall commit

packages/gf/PKGBUILD, packages/python-pybase64/PKGBUILD
Hi there!
Created a PKGBUILD for python-pybase64.
Hope it's alright.
Cheers!
=> Python pybase64: initial commit.

lists/to-release, packages/pass-station/PKGBUILD
also change source to actively maintained fork
=> pass-station: version bump

packages/v3n0m/PKGBUILD
- fix most upstream issues
- ensure Poetry install from PKGBUILD
Please email either @kattstof or myself for additional information.
=> v3n0m: fix installation error

packages/obevilion/PKGBUILD
the pipe was breaking website parsing
=> obevilion: fix website parsing

lists/to-release, packages/s3scanner/PKGBUILD
Not working  --
The fix:
repackage s3scanner with pypi template update and build --
using pyproject.toml installation method --
please review --
=> + s3scanner package update; fix

packages/git-dumper/PKGBUILD
Modify git-dumper recipe for work with last changes
=> Modify git-dumper recipe

packages/autorecon/PKGBUILD
https://github.com/Tib3rius/AutoRecon/blob/fec09fb59113b8c6acaaabde5f9049e8604ccee6/pyproject.toml#L14
=> autorecon: add missing dep

mirror/mirror.lst
=> Added SG.GS [SG] mirror

mirror/mirror.lst
fix https://github.com/BlackArch/blackarch/issues/3423
=> add Berkeley mirror

lists/to-release, packages/whatwaf/PKGBUILD, packages/whatwaf/PatchFile
Please review --
Patch for Python3 and to keep this from crashing --
=> + whatwaf python3 fix

packages/catana/PKGBUILD
Updated pkgvers. Fixed Quit command by implementing custom exit function for exiting from both the local function and the main program.
=> catana: version bump

packages/python-telethon/PKGBUILD
Update python-telethon from 1.13.0 to 1.24.0
Resolve  #3436
=> update: python-telethon

packages/genisys/PKGBUILD
see https://github.com/BlackArch/blackarch/issues/2759#issuecomment-1179749595
=> genisys: update dead url

packages/ligolo-ng/PKGBUILD
Add Ligolo-ng as requested in #3448.
Signed-off-by: Mariano Marciello <marciello.mariano@gmail.com>
=> add ligolo-ng

packages/stowaway/PKGBUILD
fixes #3307.
is it the same package as https://github.com/Dliv3/Venom but maybe with different features ?
=> stowaway: initial commit

packages/bopscrk/PKGBUILD
=> bopscrk: better packaging

packages/gmsadumper/PKGBUILD
fix https://github.com/BlackArch/blackarch/pull/3216#pullrequestreview-730135625 thx to https://github.com/micahvandeusen/gMSADumper/issues/3#issuecomment-1196021041 resolution
=> gmsadumper: update and add license

packages/crackql/PKGBUILD, packages/crackql/crackql.install
please review. pyproject.toml added by the gents.
=> crackql fixes #3489

packages/python-minikerberos/PKGBUILD
- better source (auto)
- add 2 missing deps
=> python-minikerberos: various enhancements

lists/to-release, packages/mugshot/PKGBUILD
=> mugshot: fix build

lists/to-release, packages/python-aiosmb/PKGBUILD, packages/python-asyauth/PKGBUILD, packages/python-msldap/PKGBUILD, packages/python-pypykatz/PKGBUILD, packages/python-winacl/PKGBUILD
=> python-pypykatz

lists/to-release, packages/certipy/PKGBUILD
=> add certipy

lists/to-release, packages/donpapi/PKGBUILD, packages/python-lnkparse3/PKGBUILD, packages/python-m2crypto/PKGBUILD
TODO
Tested with:
```
$ ba-dev -I ../python-m2crypto/python-m2crypto-0.38.0-1-any.pkg.tar.zst ../python-lnkparse3/python-lnkparse3-1.2.0-1-any.pkg.tar.zst
$ ba-dev -e 'donpapi -h' -p donpapi-v1.0.0.r45.gf724f82-1-any.pkg.tar.zst
```
=> Add donpapi

packages/timeverter/PKGBUILD
Added PKGBUILD file for timeverter tool (source: https://github.com/D3vil0p3r/timeverter)
=> timeverter: Added timeverter tool

lists/to-release, packages/python-arsenic/PKGBUILD
https://pypi.org/project/arsenic/
please review; version bump and PKGBUILD update.
pkgver=21.8
=> #fix python-arsenic: version bump

lists/to-release, packages/commentor/PKGBUILD
Added PKGBUILD file for commentor tool (source: https://github.com/D3vil0p3r/comMENTOR)
=> commentor: Added commentor tool

packages/clairvoyance/PKGBUILD
=> clairvoyance: add package

lists/to-release, packages/mobsf/PKGBUILD, packages/python-svgutils/PKGBUILD
- add missing dependencies
- remove useless dependencies
- re-order dependencies in a maintainable way
=> mobsf: clean dependencies

packages/peass/PKGBUILD
- use release in pkgver
- update upstream url
- fix the tree and deployment
- build linux script locally
- download missing binaries
fixes #3649
replaces #3645
=> peass: update and fix

packages/bloodhound/PKGBUILD
fix #3674
@D3vil0p3r Could you test it please? 😃
=> blodhound: old openssl

packages/evil-winrm/PKGBUILD
cf. https://github.com/BlackArch/blackarch/pull/3620#issuecomment-1339237700
=> evil-winrm: try workaround idea

packages/sub3suite/PKGBUILD
A free, open source, cross platform Intelligence gathering tool.
Source: https://github.com/3nock/sub3suite
Compiling details: https://github.com/3nock/sub3suite/blob/main/COMPILING.md
=> sub3suite: add package

lists/to-remove
Details: https://github.com/georgiaw/Smartphone-Pentest-Framework
=> smartphone-pentest-framework: add to to-remove

packages/bqm/PKGBUILD, packages/clairvoyance/PKGBUILD, packages/ctf-party/PKGBUILD, packages/haiti/PKGBUILD
All packages were tested building and running.
=> version bumps

lists/broken, packages/katana-framework/PKGBUILD, packages/katana-pd/PKGBUILD
fix #3612
- Rename the current katana (https://github.com/PowerScript/KatanaFramework) to katana-framework
- Add katana (https://github.com/projectdiscovery/katana)
- deprecate katana-framework
- add some of the missing dependencies for katana-framework
=> add katana (pd) and rename/rework katana (framework)

packages/go-windapsearch/PKGBUILD
=> go-windapsearch: add package

packages/crackmapexec/PKGBUILD, packages/python-masky/PKGBUILD
=> python-masky: add package

packages/ffuf/PKGBUILD
=> ffuf: bump from 1.5 to 2.0

packages/python-aiosmtplib/PKGBUILD, packages/python-vtapi3/PKGBUILD
issue fixed upstream, workaround no longer needed
=> remove temporary fix

lists/to-release, packages/python-minikerberos/PKGBUILD
https://github.com/skelsec/minikerberos/pull/30
Should I insert `python-minikerberos` in `to-release` file?
=> solving tests folder in python3.10 root folder

packages/turner/PKGBUILD
=> turner: add package

packages/apachetomcatscanner/PKGBUILD, packages/python-sectools/PKGBUILD
@p0dalirius I added your tool to BlackArch Linux 😉
=> apachetomcatscanner : add package

packages/airgeddon/PKGBUILD
=> airgeddon: bump version + new optdep

packages/sprayhound/PKGBUILD
=> add sprayhound

packages/rusthound/PKGBUILD
Bringing RustHound to BlackArch
fix #3773
cc @g0h4n
=> rusthound: add package

packages/githound/PKGBUILD
I used a jointscript because the binary is looking for the config file(s) from working directory.
cc @tillson
=> githound: add package

lists/to-release, packages/mrkaplan/PKGBUILD
As agreed with @noraj on https://github.com/BlackArch/blackarch/pull/3766#event-8959172277
=> mrkaplan: fixing PKGBUILD structure

packages/sonar-scanner/PKGBUILD
=> sonar-scanner: add package

mirror/mirror.lst
fix https://github.com/BlackArch/blackarch/issues/3832
also see https://github.com/BlackArch/blackarch-site/pull/174
=> remove unmaintained mirrors

lists/to-release, packages/rbac-lookup/PKGBUILD
=> initial comment; rbac-lookup

packages/padding-oracle-attacker/PKGBUILD
=> add padding-oracle-attacker

lists/to-release, packages/peach-fuzz/PKGBUILD
Changed pwntools to python-pwntools: #3859
=> peach-fuzz: fixed pwntools dependency

lists/to-release, packages/zeratool/PKGBUILD
Changed pwntools to python-pwntools: #3859
=> zeratool: fixed pwntools dependency

lists/to-release, packages/wordlistctl/PKGBUILD
repo.json updated; package bump; new assetnote.io 2023 urls included
wordlistctl version bump -> v0.9.4
Please review.
Thanks !
=> v0.9.4 version bump

lists/to-release, packages/python-lsassy/PKGBUILD
Updated to the latest commit that fixes the conflicting issues with other BA packages. Thank you @noraj for your latest commit on [lsassy](https://github.com/Hackndo/lsassy/pull/85)
=> fixed: python-lsassy

lists/to-release, packages/python-dsinternals/PKGBUILD
Temporary fix of tests conflicting error.
Ref: https://github.com/p0dalirius/pydsinternals/pull/11
Thank you for the PR on the source project @noraj
=> fixed: python-dsinternals

packages/ddosify/PKGBUILD
=> ddosify: version bump

packages/phoneinfoga/PKGBUILD
Updated phoneinfoga to v2.10.7
=> Bump phoneinfoga

packages/bss/PKGBUILD
Modify the destination filename to avoid error: failed to commit transaction (conflicting files)
=> bss; Update PKGBUILD to avoid conflicting files error

lists/to-release, packages/ares/PKGBUILD
https://github.com/bee-san/Ares Interesting AI-based decoder and decrypter.
=> added: ares

packages/donpapi/PKGBUILD
the structure as changed, it was no longer building, there was no longer a `DonPAPI.py` script
also the package `donpapi` wasn't available in the repository
=> donpapi: fix build

lists/to-release, packages/gvm-libs/PKGBUILD, packages/openvas-scanner/PKGBUILD
It fixes an issue related to an old lib.
=> openvas-scanner: version bump

packages/pin/PKGBUILD
=> pin: version bump

packages/ligolo-ng/PKGBUILD
=> ligolo-ng: version bump

lists/to-release, packages/python-pyshark/PKGBUILD
Fix some issues related to py.io
=> python-pyshark: bump version

packages/c7decrypt/PKGBUILD
There are no dependencies, updates are not frequent, very easy to maintain.
=> add c7decrypt

packages/padoracle/PKGBUILD
=> add padoracle

packages/networkminer/PKGBUILD
https://www.netresec.com/?page=Blog&month=2023-10&post=NetworkMiner-2-8-1-Released
=> NetworkMiner 2.8.1 released

lists/to-release, packages/s3scanner/PKGBUILD
please review. Will adjust pkgver; Well.. actually let me know about this. Full rewrite in go.
Thanks !
=> #3976 s3scanner go

packages/nuclei-templates/PKGBUILD, packages/nuclei/PKGBUILD
details in commit message
fix #3987
=> nuclei update and fix

packages/anubis/PKGBUILD
=> Add anubis

packages/adfind/PKGBUILD
after upgrading adfind from old php version to a new golang we also need to update PKGBUILD for properly install
=> Update PKGBUILD (adfind)

packages/crackpkcs12/PKGBUILD
=> add crackpkcs12

lists/to-release, packages/puredns/PKGBUILD
Please review.
Thank you.
closes #4023
=> #4023 puredns initial commit

packages/ntlm_theft/PKGBUILD
=> add ntlm_theft

packages/semgrep/PKGBUILD
- bump pkgver
- fix build error due to _py outdated
- add new dependency missing
- fix sg conflict
=> semgrep: update & various fixes

packages/mantra/PKGBUILD
=> add mantra

packages/ruby-http_configuration/PKGBUILD, packages/ruby-terminal-table/PKGBUILD
about https://github.com/BlackArch/blackarch/discussions/4086
=> update some licenses

packages/snyk/.gitignore, packages/snyk/PKGBUILD
replacing #4096 in a wait of a history cleaning
=> snyk: update, fix url & remove binary from git

packages/semgrep/PKGBUILD
replacing https://github.com/BlackArch/blackarch/pull/4096 in a wait of a history cleaning
=> semgrep: update

packages/swt/PKGBUILD, packages/swt/build-swt.xml
=> swt: update to 4.31 and fix build

packages/certipy/PKGBUILD
add missing dep + fix version required
=> fix certipy

packages/bopscrk/PKGBUILD
fix #4110
https://github.com/r3nt0n/bopscrk/blob/master/requirements.txt
=> bopscrk: fix missing dep

packages/passdetective/PKGBUILD
=> add passdetective

packages/ldeep/PKGBUILD
- add missing runtime dependencies
- add missing build dependency
- better pkgver
=> ldeep: fix package

packages/kamerka/PKGBUILD, packages/python-folium/PKGBUILD, packages/python-xyzservices/PKGBUILD
https://github.com/BlackArch/blackarch/issues/4141#issuecomment-2118982785
=> fix kamerka

mirror/mirror.lst
Greetings,
The mirror list has been updating from http://mirror.team-cymru.com to https://mirror.team-cymru.com
Thanks
=> Update mirror.lst team-cymru.com from http to https

packages/conpass/PKGBUILD
=> add conpass

packages/krbjack/PKGBUILD
=> add krbjack

packages/feroxbuster/PKGBUILD
- disable LTO
- add missing system requirements
fix #4163
=> feroxbuster: fix package

lists/to-release, packages/whoxyrm/PKGBUILD
=> add whoxyrm

packages/netexec/PKGBUILD
- poetry can't install system dependencies
=> netexec: fix dependency

packages/assassingo/PKGBUILD
=> add assassingo

packages/arping/PKGBUILD
=> add arping

packages/sherlock/PKGBUILD
- move to PEP517 packaging
- remove useless dependencies
- add missing dependency
also fix #4191
=> sherlock: major packing update

packages/plcscan/PKGBUILD, packages/pmcma/PKGBUILD
=> update plcscan source

lists/to-release, packages/villain/PKGBUILD
Solve https://github.com/BlackArch/blackarch/issues/4207
=> villain: add package

packages/emp3r0r/PKGBUILD, packages/mubeng/PKGBUILD, packages/sickle/PKGBUILD
=> upgpkg: sickle

packages/terminus-font-ttf/PKGBUILD
=> upgpkg: terminus-font-ttf

packages/wpsweep/PKGBUILD
ntsercurity.nu -> vidstromlabs.com
https://paste.fo/raw/0fda0c63dafc <- similar relocated packages
=> wpsweep moved

lists/broken
Close https://github.com/BlackArch/blackarch/issues/3525
=> sprayingtoolkit: broken

mirror/mirror.lst
Close https://github.com/BlackArch/blackarch/issues/3860
Opened PR also on blackarch-site repo: https://github.com/BlackArch/blackarch-site/pull/193
=> Remove non-existing mirror

lists/broken
https://github.com/BlackArch/blackarch/issues/3757
=> tracedump: broken list

lists/to-release, packages/lte-cell-scanner/PKGBUILD
Close https://github.com/BlackArch/blackarch/issues/3801
The proposed update enables also several modules.
=> lte-cell-scanner: update package

lists/to-release, packages/hostapd-wpe/0001_adj-wpe.patch, packages/hostapd-wpe/PKGBUILD, packages/hostapd-wpe/hostapd-wpe.install
Close https://github.com/BlackArch/blackarch/issues/3980
=> hostapd-wpe: version bump

lists/to-release, packages/fluxion/PKGBUILD
Close https://github.com/BlackArch/blackarch/issues/4137
Fixed deps
=> fluxion: version bump

packages/wce/PKGBUILD, packages/wkhtmltopdf/PKGBUILD
=> add dep for wkhtmltopdf

lists/broken
Close https://github.com/BlackArch/blackarch/issues/4161
=> pth-toolkit: broken

packages/panoptic/PKGBUILD
=> panoptic build

packages/urlcrazy/PKGBUILD
web page is outdated, their git seems inactive (2019) but still years newer than 0.5...
=> upgpkg: urlcrazy 0.7.3

lists/to-release, packages/ghostpack/PKGBUILD
https://github.com/r3motecontrol/Ghostpack-CompiledBinaries/issues/5
=> ghostpack: bump to .NET 4.8.1

lists/to-release, packages/waymore/PKGBUILD
Close https://github.com/BlackArch/blackarch/issues/3741
=> waymore: add package

lists/broken
https://github.com/BlackArch/blackarch/issues/2761
=> idb: broken

lists/broken
https://github.com/BlackArch/blackarch/issues/2494
=> shellcodecs: broken

lists/broken
https://github.com/BlackArch/blackarch/issues/2494
=> metoscan: broken

lists/to-release, packages/vncrack/PKGBUILD
https://github.com/BlackArch/blackarch/issues/2494
=> vncrack: update source and fix building issues

lists/to-release, packages/crowbar/PKGBUILD
https://github.com/BlackArch/blackarch/pull/4280#issuecomment-2453054670
=> crowbar: fix license and PKGBUILD template base

lists/to-release, packages/sdrtrunk/PKGBUILD, packages/sdrtrunk/sdrtrunk.desktop
Close https://github.com/BlackArch/blackarch/issues/3783
=> sdrtrunk: add package

lists/broken
Close https://github.com/BlackArch/blackarch/issues/4087
=> levye: broken

lists/to-release, packages/pyinstxtractor/PKGBUILD
Close https://github.com/BlackArch/blackarch/issues/3631
=> pyinstxtractor: add package

lists/to-release, packages/arjun/PKGBUILD, packages/python-ratelimit/PKGBUILD
Close https://github.com/BlackArch/blackarch/issues/4331
=> arjun: fix dependency

packages/certsync/PKGBUILD
=> certsync: bump version

packages/impacket-ba/PKGBUILD
=> impacket-ba: bump version

lists/to-release, packages/ike-scan/0001-Use-zu-instead-of-u-printf-format-for-size_t.patch, packages/ike-scan/0002-Use-printf-ld-format-for-timeval-tv_usec-field.patch, packages/ike-scan/0003-acinclude.m4-fix-Wimplicit-int-errors-Clang-16-compa.patch, packages/ike-scan/0004-acinclude.m4-fix-typo-in-x-if-check.patch, packages/ike-scan/0005-configure.ac-Fix-recognising-Wformat-security-with-C.patch, packages/ike-scan/0006-Removed-obsolete-autoconf-macros.-Incremented-versio.patch, packages/ike-scan/PKGBUILD, packages/ike-scan/acinclude.m4-Fix-Werror-implicit-function-declaration.patch, packages/ike-scan/disable_aggressive_in_v2.patch, packages/ike-scan/skip-malformed-comp.patch
Fix build error related to the usage of 64-bit integer.
Close https://github.com/BlackArch/blackarch/issues/2494
=> ike-scan: fix build error

lists/to-release, packages/python-libusb/PKGBUILD, packages/python-pkg_about/PKGBUILD, packages/rfcrack/PKGBUILD
Close: https://github.com/BlackArch/blackarch/issues/3808
Need: https://github.com/BlackArch/blackarch/pull/4266
=> rfcrack: add package

lists/to-release, packages/spektrum/PKGBUILD
Close https://github.com/BlackArch/blackarch/issues/3810
=> spektrum: add package

lists/to-release, lists/to-remove, packages/rtl8814au-dkms-git/PKGBUILD, packages/rtl8814au-dkms-git/arm.patch, packages/rtl8814au-dkms-git/dkms.conf
Close https://github.com/BlackArch/blackarch/issues/3646
=> rtl8814au-dkms-git: add package

lists/to-release, packages/assetnote-wordlists/PKGBUILD
Close https://github.com/BlackArch/blackarch/issues/3052
=> assetnote-wordlists: add package

lists/to-release, packages/attk/PKGBUILD, packages/dmde/PKGBUILD
Remove "arch" duplicated entries and update dmde.
=> Remove duplicated "arch" entries

lists/to-release, packages/threat-dragon/PKGBUILD
Close https://github.com/BlackArch/blackarch/issues/2393
=> threat-dragon: add package

packages/adpeas/PKGBUILD, packages/certi/PKGBUILD
=> add adpeas & certi

packages/breads/PKGBUILD
=> add breads

lists/to-release, packages/qradiolink/PKGBUILD
Close https://github.com/BlackArch/blackarch/issues/3781
=> qradiolink: add package

packages/gpowned/PKGBUILD
related to #4353 
waiting for a license https://github.com/X-C3LL/GPOwned/issues/4
=> add gpowned

lists/to-release, packages/apkid/PKGBUILD, packages/python-yara-python-dex/PKGBUILD, packages/ssma/PKGBUILD
Close https://github.com/BlackArch/blackarch/pull/3630 and https://github.com/BlackArch/blackarch/issues/3296
=> python-yara-python-dex: add package and replace rednaga

lists/to-release, packages/csdr/PKGBUILD, packages/openwebrx/PKGBUILD, packages/owrx_connector/PKGBUILD, packages/python-js8py/PKGBUILD, packages/python-pycsdr/PKGBUILD
Close https://github.com/BlackArch/blackarch/issues/3784
=> openwebrx: add package

packages/navgix/PKGBUILD
=> navgix: initial commit.

packages/cudahashcat/PKGBUILD
=> pkgrel: cudahashcat sha+syntax

packages/ldapmonitor/PKGBUILD
=> add ldapmonitor

lists/to-release, packages/netspionage/PKGBUILD
Close https://github.com/BlackArch/blackarch/issues/3946
Merged https://github.com/ANG13T/netspionage/pull/5
Merged https://github.com/ANG13T/netspionage/pull/6
=> netspionage: add package

packages/netscout/PKGBUILD
=> add netscout

packages/python-aiowmi/PKGBUILD
=> add python-aiowmi

packages/sccmhunter/PKGBUILD
=> add sccmhunter

packages/targetedkerberoast/PKGBUILD
=> add targetedkerberoast

lists/to-release, packages/smtp-user-enum/Fix-missing-T-option-in-getopts-declaration.patch, packages/smtp-user-enum/Fix-timeout-option-by-changing-it-to-w.patch, packages/smtp-user-enum/PKGBUILD, packages/smtp-user-enum/fix-usage-output
Close https://github.com/BlackArch/blackarch/issues/4428
=> smtp-user-enum: patch wrong argument

packages/bloodhound-python-ce/PKGBUILD, packages/bloodhound-python/PKGBUILD
changes for new bloodhound.py collector https://x.com/_dirkjan/status/1874857411292639414
=> bloodhound.py changes + CE version

packages/bloodhound-python-ce/PKGBUILD
patch for https://github.com/dirkjanm/BloodHound.py/issues/206
=> patch to prevent conflicts with bloodhound-python package

packages/sleuthkit-java/PKGBUILD
Use more recent jdk to fix missing jni dependency
=> sleuthkit-java: Fix build process based on AUR pkg

packages/burpsuite/PKGBUILD
fix https://github.com/BlackArch/blackarch/issues/4452
=> burpsuite: update to 2025 release

packages/kamerka/PKGBUILD, packages/kamerka/kamerka.install
Updated the package kamerka to a "working" fork.
=> kamerka: update package.

lists/to-release, packages/gpp-decrypt/PKGBUILD
Close https://github.com/BlackArch/blackarch/issues/4444
=> gpp-decrypt: add package

packages/above/PKGBUILD
replaces #4481, #4465, #4464
cc @s7x
=> above: add package

packages/dnsrecon/PKGBUILD
=> dnsrecon: fix missing dependencies

lists/to-release, packages/theharvester/PKGBUILD
Missing dependency added
package bump
Please Review
=> #fix missing python-dateutil

packages/urx/PKGBUILD
Created package [urx](https://github.com/hahwul/urx) by [@hahwul](https://github.com/hahwul).
=> urx: initial commit.

packages/networkminer/PKGBUILD
https://netresec.com/?b=254caa9
=> NetworkMiner 3.0 Released

packages/python-defusedcsv/PKGBUILD
Originally from: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-defusedcsv
=> python-defusedcsv: add package

packages/dirsearch/PKGBUILD
Waiting for:
+ #4550
+ #4551
See https://github.com/maurosoria/dirsearch/blob/master/requirements.txt
=> dirsearch: update dependency

lists/python2-tools, lists/to-release, packages/nsec3map/PKGBUILD
Hi there.
Package is updated to python3.
Cheers!
=> nsec3map: python3 support.

mirror/mirror.lst
=> add miraa mirrors

packages/subzy/PKGBUILD
=> subzy: add package

packages/java17-openjfx-bin/PKGBUILD, packages/java21-openjfx-bin/PKGBUILD, packages/java24-openjfx-bin/PKGBUILD, packages/recaf/PKGBUILD
- packages 3 version of openjfx
- upgrade recaf to v4
=> recaf: upgrade to v4

packages/wdict/PKGBUILD
Added the package wdict. An alternative to cewl in Rust, made by @pyqlsa.
=> wdict: initial commit.

packages/whatweb/PKGBUILD
- update pkgver()
- add prepare() to fix missing dependencies until upstream is fixed
- fix the wrapper that wasn't using the virtualenv
=> whatweb: fix package

packages/typo3scan/PKGBUILD
- fix license
- fix missing dependencies
- update package version function
=> typo3scan: fix package

lists/to-remove
https://github.com/BlackArch/blackarch/issues/4302
=> proxmark: remove due to AL proxmark3 package

lists/to-release, packages/jinjector/PKGBUILD
Close https://github.com/BlackArch/blackarch/issues/4528
=> jinjector: add package

lists/python2-tools, lists/to-release, lists/to-remove, packages/aclpwn/PKGBUILD, packages/activedirectoryenum/PKGBUILD, packages/impacket-ba/PKGBUILD, packages/python2-ldapdomaindump/PKGBUILD
Close https://github.com/BlackArch/blackarch/issues/4557
=> ldapdomaindump: to remove

lists/to-release, packages/mercury/PKGBUILD
Close https://github.com/BlackArch/blackarch/issues/2667
=> mercury: fix building errors

packages/extractbitlockerkeys/PKGBUILD
=> add extractbitlockerkeys

lists/broken
Close https://github.com/BlackArch/blackarch/issues/2759
=> Added broken packages

lists/to-release, packages/firewalk/PKGBUILD, packages/firewalk/fix-signals.patch
Ref https://github.com/BlackArch/blackarch/issues/4546
=> firewalk: fix building errors

lists/to-release, packages/inviteflood/PKGBUILD, packages/inviteflood/add-missing-flag.patch, packages/inviteflood/add-missing-includes.patch
Ref https://github.com/BlackArch/blackarch/issues/4546
=> inviteflood: fix build error

lists/to-release, packages/rtpbreak/PKGBUILD, packages/rtpbreak/add-missing-debug-flag.patch, packages/rtpbreak/add-missing-include.patch, packages/rtpbreak/fix-format-security.patch
Ref https://github.com/BlackArch/blackarch/issues/4546
=> rtpbreak: fix build error

lists/broken, lists/to-release, packages/ndpi/PKGBUILD, packages/xplico/Adapt-code-for-ndpi-4.x.patch, packages/xplico/Don-t-include-private-json-c-header.patch, packages/xplico/Fix-Makefile-to-keep-hardening-flags-injected-by-dpkg.patch, packages/xplico/Fix-upstream-makefile-to-not-fudge-with-the-debian-dir.patch, packages/xplico/Improve-systemd-service-file.patch, packages/xplico/PKGBUILD, packages/xplico/add-more-explicit-message.patch, packages/xplico/cake-Fix-SchemaShell-configuration-change.patch, packages/xplico/cake-Fix-argument-order-for-implode-method.patch, packages/xplico/cake-Fix-deprecated-argument-order-in-calls-to-implode.patch, packages/xplico/cake-Fix-failures-on-PHP-7.4.patch, packages/xplico/cake-Fix-invalid-data-type.patch, packages/xplico/cake-Fix-shutdown-warnings-in-PHP7.2.patch, packages/xplico/cake-Make-TestShell-compatible-with-PHP-7.4.patch, packages/xplico/cake-php-7.4-Replace-deprecated-curly-brace-offset.patch, packages/xplico/cake-php-8-Fix-error-unknown-named-parameter-subject.patch, packages/xplico/change-default-config-file.patch, packages/xplico/change-path-to-ndpi.patch, packages/xplico/fix-bool-typedef.patch, packages/xplico/fix-spelling-errors.patch, packages/xplico/fix-sql.patch, packages/xplico/ndpi4-support.patch, packages/xplico/search-php.ini-in-correct-location.patch, packages/xplico/update-for-ndpi-3.x.patch
Solve https://github.com/BlackArch/blackarch/issues/3661
=> xplico: fix building errors

packages/darkdump/PKGBUILD, packages/darkdump/darkdump.install
Fixed the darkdump package that was not working properly. Was forced to use the venv technique, haven't figured out why.
Cheers!
=> darkdump: fix package.

mirror/mirror.lst
=> Add MeowSMP.net Mirror

mirror/mirror.lst
replaces #3856
related to https://github.com/BlackArch/blackarch-site/pull/177
=> add 0xemma mirror
