BlackArch/blackarch

packages/nsia/PKGBUILD
packages/nsia/nsia.install

The strangely named /var/lib/nsia/var directory was not created by the PKGBUILD's package() function, and the post-install script runs recursive group and mode changes on the root directory, destroying existing installations. These changes correct this oversight.

Fix extremely dangerous failing post-install script.

---

packages/metasploit/PKGBUILD

Metasploit binary package fails to install correctly unless libxslt is present, added the dependency to PKGBUILD.

Updated metasploit dependencies

---

packages/maltego/PKGBUILD

Extide directory is need for maltego and you are forgot to copy that directory in PKGBUILD file

Forgot copy extide directory to /usr/share/maltego in PKGBUILD

---

packages/winexe/PKGBUILD
packages/winexe/gnutls.patch
packages/winexe/pidl.patch

Winexe did not work since gnutls versions > 3.0.0.
Also some perl problems with `defined`.
Please note that Sourceforge is currently having some issues, so you may need to download the source by hand.

winexe: fix for gnutls > 3.0.0

---

packages/recon-ng/PKGBUILD

I was trying to run today recon-ng on my own blackarch system for a pentest and notice it was outdated and was not able to run. so forked the project and did the changes for me locally, then i decided to push the change upstream so other people can also use it.

recon-ng upgraded to version 4.6.3

---

packages/elite-proxy-finder/PKGBUILD

The `python2-beautifulsoup3` dependency was missing

Fix `elite-proxy-finder` missing dependency

---

packages/checkpwd/PKGBUILD

checkpwd tool is a 32-BIT ELF.
therefore, it requires the 32-BIT version of libcrypto LSB\
---
**`$ yaourt -Qi checkpwd`**
```
Name           : checkpwd
Version        : 1.23-3
Description    : Oracle Password Checker (Cracker).
Architecture   : x86_64
URL            : http://www.red-database-security.com/software/checkpwd.html
Licenses       : GPL
Groups         : blackarch  blackarch-cracker
Provides       : None
Depends On     : unixodbc  zlib  libstdc++5
Optional Deps  : None
Required By    : None
Optional For   : None
Conflicts With : None
Replaces       : None
Installed Size : 116.03 MiB
Packager       : Levon Kayan <noptrix@nullsecurity.net>
Build Date     : Sun 22 Mar 2015 03:04:49 PM CET
Install Date   : Tue 17 Nov 2015 11:58:59 PM CET
Install Reason : Explicitly installed …
```

Fix libcrypto 32-BIT forgotten dependency

---

packages/set/PKGBUILD

tabulations replacements in `setoolkit` file caused lines 194 to 197 to be missindented,
making set command unusable on the main menu loop.

Fix 'set' PKGBUILD's indentation patch

---

packages/sipsak/PKGBUILD

**Without c-ares package installed, running sipsak produced the following error:**
```
$ sipsak
sipsak: error while loading shared libraries: libcares.so.2: cannot open shared object file: No such file or directory
```

Add missing dependency on 'sipsak' package

---

packages/secure-delete/PKGBUILD

secure-delete is conflict with package srm, so there is no need to rename /usr/bin/srm.
better to rename man page of smem to avoid confusion.

secure-delete: Fix conflicts

---

packages/recon-ng/PKGBUILD

Hello again :) sorry to keep sending pull request for different packages, I work as a pentester and when some packages get behind I have to modify the package to install it.. in some cases like recon-ng I can't even use it unless I update, so figure to sent upstream my changes, i'm sure if there is other professional pentesters using blackarch they will be happy to see the version bump. Cheers.

recon-ng version bump to 4.8.0

---

packages/recon-ng/PKGBUILD

If not installed, recon-ng disables the `metacrawler` module:
```
[!] Module 'recon/domains-contacts/metacrawler' disabled. Dependency
required: 'olefile'.
```
* the binaries reated were not working properly:
- add '$@' on binary calls to be able to pass arguments
- fix working directory to `/usr/share/recon-ng`
* cleanout PKGBUILD:
- REQUIREMENTS VERSION were not properly deleted,
added them to the list of rm items.
dependencies tested and added according to
`recon-ng/REQUIREMENTS` file.

recon-ng: error fix and version upgrade

---

packages/dump1090/PKGBUILD

Fixes the location of public_html directory in `dump1090` so that it can show the map correctly when run with `--net`.

dump1090: Fixed public_html location

---

packages/vcsmap/PKGBUILD

Thanks for including vcsmap in BlackArch!
Today I released a new version that fixes a change in GitHub. This is an important update. Because I noticed that vcsmap is included in BlackArch I also made it easier to find the right directory (see: https://github.com/melvinsh/vcsmap/commit/6fba205d8d8fe32365775c32373d135cc6c4cf82). 
This is my first edit to a `PKGBUILD`, so I hope I got it right.

Vcsmap version bump

---

packages/blackmate/PKGBUILD

On a fresh xfce4 install it work, I add the needed deps for avoid any fail with blackmate. It now only work for xfce4, mate wm support was removed since it sucks. please check the deps I add for confirm everything is in order before to merge

Updated and tested this day

---

packages/oletools/PKGBUILD

Without the arguments ($@) the wrappers only show builtin help
Ex:
```
$ oleid suspicious.doc 
Usage: 
oleid.py
oleid is a script to analyze OLE files such as MS Office documents (e.g. Word,
Excel), to detect specific characteristics that could potentially indicate that
the file is suspicious or malicious, in terms of security (e.g. malware).
For example it can detect VBA macros, embedded Flash objects, fragmentation.
The results can be displayed or returned as XML for further processing.
Usage: oleid.py <file>
oleid project website: http://www.decalage.info/python/oleid
oleid is part of the python-oletools package:
http://www.decalage.info/python/oletools
usage: oleid.py [options] <file>
Options:
-h, --help  show this help message and exit
```
```
$ cat `which oleid`
#!/bin/sh
exec …
```

Pass arguments to oletools /usr/bin/ wrappers

---

packages/dff/PKGBUILD
packages/dff/fixes.patch
packages/libbde/PKGBUILD
packages/libbfio/PKGBUILD
packages/libpff/PKGBUILD
packages/libvshadow/PKGBUILD
packages/reglookup/PKGBUILD

New tool: DFF (Digital Forensics Framework) (https://github.com/arxsys/dff)
Dependencies (built from latest Github libyal sources):
- libbde (https://github.com/libyal/libbde)
- libbfio (https://github.com/libyal/libbfio)
- libpff (https://github.com/libyal/libpff)
- libvshadow (https://github.com/libyal/libvshadow)
Edited dependencies:
- libewf to build from latest Github libyal sources (https://github.com/libyal/libewf)
- reglookup to copy site-packages from
python 3.6 to 2.7 as last package() step to support Python 2, ultimately DFF

New tool: DFF (w/ dependencies)

---

packages/dradis-ce/PKGBUILD
packages/dradis-ce/dradis.install
packages/dradis-ce/dradis.patch

I've finally found some time to look at the non-legacy dradis, dradis-ce.
To make it usable without running rails as root a few files and folders in `/usr/share/dradis-ce`  are made world writable, which is probably not the best way to approach this – I'm open to suggestions for better ways to handle this situation: maybe by creating a dradis-user who can write in those folders and launching dradis/rails with a service?

new tool: dradis-ce

---

packages/set/PKGBUILD

Fix 'set' PKGBUILD to close BlackArch/blackarch#1532
The indention fix seems no longer to apply

Fix 'set' PKGBUILD

---

packages/wifi-pumpkin/PKGBUILD

The Problem i see here is, that if pip is used to install dependencies, they wont be removed on uninstall.
This adresses BlackArch/blackarch#1533

Add dependencies for wifi-pumpkin

---

packages/veil/PKGBUILD
packages/veil/setupsh_mod.patch
packages/veil/veil.install

So I tried to get this working again. Man, I don't like its install process..
Anyway: As before Go payloads currently fail. I'll see that I'll actually get this done somehow this time, but not today, I guess. It would be nice to get this working without using gcc-go, which conflicts with gcc..
Also during Ruby payload generation ocra semi-silently fails:
```
C:/Ruby187/lib/ruby/gems/1.8/gems/ocra-1.3.6/bin/ocra:1040:in `initialize': Permission denied - tmpin (Errno::EACCES)
```
..even though directly executing _exactly_ the os.system call veil uses doesn't fail. I'm not sure if that's an issue with my kernel (grsec) and wine or something else – if anyone feels like testing or has an idea I'm all ears.
Should (somewhat) fix #1598

update to veil 3

---

packages/cyberScan/PKGBUILD

CyberScan is able to send and capture packets of several protocols, forging and decoding them to be used to most network tasks such as scanning, pinging, probing, and attacks.
https://github.com/medbenali/CyberScan
I have the honor to add it in Black Arch

Add New Tool : CyberScan

---

packages/sylkie/PKGBUILD

- Add the [ENABLE_SETUID](https://github.com/dlrobertson/sylkie/wiki#build-options) build option
- Move libseccomp from makedepends to depends. We don't statically link
against it.

Update sylkie PKGBUILD

---

packages/beef/PKGBUILD

Beef wouldn't build without `libxslt` because `nokogiri` is being built with system libraries.

Added libxslt as a dependency for beef

---

packages/awsbucketdump/PKGBUILD

@noptrix, a review is necessary; I believe. Because I wasn't sure where to but the wordlists.
And I have "changed" the application name to `AWSBucketDump.py` to `awsbucketdump`.
This pull address: https://github.com/BlackArch/blackarch/issues/1723

[tool request] [attention] Adding AWSBucketDump.

---

packages/sandsifter/PKGBUILD

https://github.com/BlackArch/blackarch/issues/1741
**I believe someone should review this Pull Request in order to confirm everything is the way it should be.**
Tested on a virtual machine running:
`Linux blackarch 4.11.4-1-ARCH #1 SMP PREEMPT Fri Jun 9 07:46:48 CEST 2017 x86_64 GNU/Linux`
**Installing log:**
```
Suppresed message about root.
==> Making package: sandsifter 1.dff6324-1 (Tue Aug 22 02:09:20 UTC 2017)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
-> Cloning sandsifter git repo...
Cloning into bare repository '/root/testing/sifter/sandsifter'...
==> Validating source files with md5sums...
sandsifter ... Skipped
==> Extracting sources...
-> Creating working copy of sandsifter git repo...
Cloning into 'sandsifter'...
done. …
```

[tool request] [attention] sandsifter.

---

packages/goohak/PKGBUILD

Found missing another dependency on sn1per:
Sn1per/sniper: line 1021: goohak: command not found
so created the package, cheers.

Another s1per dependency called goohak

---

packages/python-pick/PKGBUILD

It's a necessary python dependency for https://github.com/BlackArch/blackarch/issues/1670

adding python-pick.

---

packages/howmanypeoplearearound/PKGBUILD

Tool request: https://github.com/BlackArch/blackarch/issues/1670
Attention: This PKGBUILD will only work after https://github.com/BlackArch/blackarch/pull/1763, since it adds a necessary python dependency (python-pick).
I couldn't test the application itself (functionality).

[tool request] adding howmanypeoplearearound

---

packages/bro/PKGBUILD

Bro 2.5.1 is now the stable release (see
https://www.bro.org/download/).
Bro requires openssl-1.0 (see
<https://bro-tracker.atlassian.net/browse/BIT-1775>) and will not work
with Archlinux openssl package (this package is currently broken).
This commit also fixes the `build()` function (using cmake).

Update and fix bro

---

packages/cower/PKGBUILD

This PKGBUILD file was extracted from AUR.
#1286 
This is a dependency for `pacaur`.

[tool request - dep] dep for pacaur.

---

packages/python-pyqtgraph/PKGBUILD

This pull request adds the package called `python-pyqtgraph`.
One of the optional dependencies for `binwalk` is `python-pyqtgraph`, which adds support for visualising entropy over a file. This package was not available in the core, extra, community, or blackarch repositories.

Add package python-pyqtgraph

---

packages/slurp/PKGBUILD

Adding `slurp` as requested on #1825.
Although I don't like cd'ing to the binary folder (usually `/usr/share/application`) and then call the binary, in this case I think it was necessary because it couldn't find the `permutation.json`. I didn't know what else I could do to avoid cd'ing, so I'm open to suggestion.

[tool] adding slurp #1825

---

packages/trizen/PKGBUILD

Adding trizen as a replacement for pacaur.
https://github.com/BlackArch/blackarch/issues/1839

trizen: requested on #1839

---

packages/sublist3r/PKGBUILD

Without URL https://blackarch.org/tools.html is broken.

sublist3r: adding url.

---

packages/fbht/PKGBUILD

Two dependencies had to be added to make fbht executable:
python2-setuptools
python2-selenium
Fix BlackArch/blackarch#1879

Update url for fbht and add two dependencies

---

packages/sn1per/PKGBUILD

sn1per script calls the path name sniper not sn1per, simple fix.

Fix to sniper address

---

packages/findsploit/PKGBUILD

- Upstream fixed the call to browser, so the `sed` for it isn't necessary anymore. (https://github.com/1N3/Findsploit/blob/master/findsploit#L14)
- I'm also adding `searchsploit` as dependency.
note: there were changes in the code (upstream) but the pkgver didn't change (git).

findsploit: fixing dep, groups and bumping pkgrel to force update.

---

packages/tcpdstat/PKGBUILD

- https://github.com/netik/tcpdstat
- a fork of: https://staff.washington.edu/dittrich/talks/core02/tools/tools.html

tcpdstat: adding new tool 'tcpdstat':

---

packages/getsploit/PKGBUILD

getsploit wouldn't launch due to not being in the second `getsploit` folder. This adds the second folder to the `/usr/bin/getsploit` file so it can be launched.

Fixed getsploit bug

---

packages/blackarch-mirrorlist/PKGBUILD

- mirroservice.org is down, due DNS expiring. We're falling back to `blackarch.org` for now.
ATTENTION: this PR should only be accepted after accepting https://github.com/BlackArch/blackarch-site/pull/97
Addressing: https://github.com/BlackArch/blackarch/issues/1961

mirror: update to match default (blackarch.org).

---

packages/python2-libbde-python/PKGBUILD

[libbde](https://github.com/BlackArch/blackarch/blob/master/packages/libbde/PKGBUILD) is already available, but missing the python2 binding, this package adds it.
@libyal

New tool: python2-libbde-python

---

packages/python2-libvshadow-python/PKGBUILD

[libvshadow](https://github.com/BlackArch/blackarch/blob/master/packages/libvshadow/PKGBUILD) is already available, but missing the python2 binding, this package adds it.
@libyal

New tool: python2-libvshadow-python

---

packages/fpdns/PKGBUILD

The fpdns package had a missing dependency (perl-net-dns) and install paths for perl modules were hardcoded for version 5.26.

fpdns: Fix install paths and dependencies

---

docs/official
packages/obfs4proxy/PKGBUILD

Package `obfsproxy` isn't in a Arch repository any more.

Added new tool: obfs4proxy

---

packages/python-tld/PKGBUILD
packages/python2-tld/PKGBUILD

The package python-tld used by photon was outdated and prevent it from starting correctly.

Update python2-tld and python-tld to 0.9.1

---

packages/badkarma/PKGBUILD

Requirements added in `/usr/share/badkarma/core/widgets.py`
```
gi.require_version('OsmGpsMap', '1.0')
gi.require_version('GtkSource', '3.0') 
```

badkarma: Add required packages

---

packages/bro/PKGBUILD

Bro 2.6 [has just been released](http://mailman.icsi.berkeley.edu/pipermail/bro/2018-November/013785.html).
See the [release notes](https://www.bro.org/sphinx/install/release-notes.html#bro-2-6).

Upgrade Bro to 2.6

---

packages/mingw-w64-headers/PKGBUILD

All headers are missing from the package since version 6.0.0-1 / ed6a26660ce114c589604a588a228d5f41886732 (ping @noptrix :wave: )
Since the purpose of this package is to ship headers, this fix aims to put them back in!
Requires `mingw-w64-gcc`.
Before:
```
$ cat > test.c << EOF
#include <stdio.h>
void main() {printf("Testing\n");}
EOF
$ i686-w64-mingw32-gcc -o test test.c
test.c:1:10: fatal error: stdio.h: No such file or directory
#include <stdio.h>
^~~~~~~~~
compilation terminated.
```
After:
```
$ i686-w64-mingw32-gcc -o test test.c
$ echo $?
0
```

mingw-w64-headers: fix missing headers

---

packages/bro/PKGBUILD

From <http://mailman.icsi.berkeley.edu/pipermail/zeek/2018-December/013848.html>:
> This release updates the embedded SQLite to version 3.26.0 to address the "Magellan" remote code execution vulnerability.  The stock Bro configuration/scripts don't use SQLite by default, but custom user scripts/packages may.
>
> This release also updates Broker to v1.1.2, which includes a minor bug fix in its Python bindings and improved support for building it as a static library.

Update to Bro 2.6.1

---

packages/skipfish/PKGBUILD

PR fixes lack of `libidn.so.11` library when executing skipfish:
`skipfish: error while loading shared libraries: libidn.so.11: cannot open shared object file: No such file or directory`

skipfish: add missing dependency

---

packages/atear/PKGBUILD

according to https://github.com/NORMA-Inc/AtEar#dependency-programs
but ` python2-sqlite` is still missing for example

add missing deps

---

packages/xortool/PKGBUILD

solve this (see https://github.com/hellman/xortool/blob/master/setup.py)
```
xortool -h            
Traceback (most recent call last):
File "/usr/bin/xortool", line 39, in <module>
from xortool.args import parse_parameters, ArgError
File "/usr/lib/python2.7/site-packages/xortool/args.py", line 4, in <module>
from docopt import docopt
ImportError: No module named docopt
```
And is now compatible with python 3

xortool: upgrade + dependency fix

---

packages/rsactftool/PKGBUILD

for this error
```
File "RsaCtfTool.py", line 15, in <module>
from Crypto.PublicKey import RSA
ImportError: No module named Crypto.PublicKey
```
`PyCrypto` is missing but not available in arch or blackarch repos. bur is available in AUR https://aur.archlinux.org/packages/python-pycrypto/
requirements.txt: https://github.com/Ganapati/RsaCtfTool/blob/master/requirements.txt
https://github.com/Ganapati/RsaCtfTool/blob/master/RsaCtfTool.py#L1 = `#!/usr/bin/env python3`

RsaCtfTool: upgrade

---

packages/miasm-git/PKGBUILD

Miasm (https://miasm.re / https://github.com/cea-sec/miasm) is a reverse engineering framework.
No release has yet been made since Miasm is "packageable" (i.e., depends only on resources that are already in Arch Linux), so for now we can only have the -git packages. I'll create another PR for the next stable release.
As a BlackArch & Miasm user, I can maintain these packages.

Add python-miasm-git and python2-miasm-git

---

packages/shodan/PKGBUILD

The Python Shodan packages require Colorama.

shodan: Correct dependencies

---

packages/ghidra/PKGBUILD

Ghidra contains many 64-bit ELF executables, including one critical to
Ghidra's proper functioning, therefore should only be packaged as an
x86_64 package.
Fix typo for java-environment in dependencies.
Remove optional dependencies - Python is not needed as Ghidra uses
Jython; however, it is not an optional dependency either as it is
already bundled as a standalone environment within Ghidra; finally, PAM
is not supported by Ghidra Server.

ghidra: Package fixes

---

packages/wascan/PKGBUILD

- Reverts BlackArch/blackarch#2307
- When wascan try to import modules from the current dir, it fails.
```
[i] Starting full scan...
[i] Starting attacks module...
Traceback (most recent call last):
File "/usr/share/wascan/wascan.py", line 118, in <module>
wascan().main()
File "/usr/share/wascan/wascan.py", line 110, in main
FullScan(kwargs,u,kwargs['data'])
File "/usr/share/wascan/lib/handler/fullscan.py", line 19, in FullScan
Attacks(kwargs,url,data)
File "/usr/share/wascan/lib/handler/attacks.py", line 19, in Attacks
for file in dirs(path):
File "/usr/share/wascan/lib/utils/dirs.py", line 13, in dirs
_ = os.listdir(path)
OSError: [Errno 2] No such file or directory: '/home/edu4rdshl/plugins/attacks/'
```

Revert "wascan: better exec file"

---

packages/webshells/PKGBUILD
packages/webshells/webshells.install

+ remove readme from /usr/share/webshells/
+ add a post-install info about where webshells were copied

Webshells: minor changes

---

packages/chameleon/PKGBUILD

Hi there!
I added the Chameleon PKGBUILD.
**Description**
*Chameleon is a tool which assists red teams in categorising their infrastructure under arbitrary categories. Currently, the tool supports arbitrary categorisation for Bluecoat, McAfee Trustedsource and IBM X-Force. However, the tool is designed in such a way that additional proxies can be added with ease.*

Added Chameleon PKGBUILD

---

packages/dirble/PKGBUILD

I've updated the pkgbuild for dirble to match its versioning scheme and license

Dirble: update license and version numbering

---

packages/python2-tldextract/PKGBUILD

e.g. 'altdns' package (which requires 'python2-tldextract') fails to run due to missing 'python2-requests-file' package.

python2-tldextract: 'python2-requests-file' is required on runtime

---

packages/tor-browser-en/PKGBUILD

zenity is not 'optdepends' anymore, it is mandatory.

tor-browser-en: zenity dependency.

---

packages/terminus-font-ttf/PKGBUILD
packages/terminus-font-ttf/terminus-font-ttf.install

Some applications require TTF support to display Terminus font.
This PR has the potential to fix #2433, but needs further tests.

terminus-font-ttf: TTF Terminus font support.

---

packages/sleuthkit-java/PKGBUILD

sleuthkit-java: Fixed jar filepath so that autopsy's symlink would be valid

---

packages/crackmapexec/PKGBUILD

fix dependency error
```
cme -h                                                                                                                                                                                                                                                                       
Traceback (most recent call last):                                                                                                                                                                                                                                             
File "/usr/bin/cme", line 6, in <module> …
```

cme: add dependency: python2-pycryptodomex

---

packages/airgeddon/PKGBUILD

https://wiki.archlinux.org/index.php/PKGBUILD#license
> The license under which the software is distributed. The licenses package (a dependency of the base meta package) contains many commonly used licenses, which are installed under /usr/share/licenses/common/. If a package is licensed under one of these licenses, the value should be set to the directory name, e.g. license=('GPL').
TL;DR: do not copy the license when it's a common one.
Use `install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"` only for custom licenses or ones that have their own copyright line liek MIT, BSD, etc.

airgeddon: remove install license

---

packages/crosstool-ng/PKGBUILD

The original URL is dead and has moved to https://crosstool-ng.github.io/
a github is available to create a git package https://github.com/crosstool-ng/crosstool-ng

crosstool-ng: update URL

---

packages/ntlmrecon/PKGBUILD

This PR adds [NTLMRecon](https://github.com/sachinkamath/ntlmrecon) to the tools.
The PKGBUILD is also [available on AUR](https://aur.archlinux.org/packages/ntlmrecon/) for testing.

NTLMRecon : Initial Commit

---

lists/to-release
packages/ruby-ctf-party/PKGBUILD
scripts/up-libraries

- fix mrsmith0x00 mess that broke the package
- add back a group since it is a targeted tool and not the dependency of another tool that is not meant to be used directly (see it as pwntool)
- remove from exclusion

fix mrsmith0x00 mess

---

packages/drozer/PKGBUILD

The PKGBUILD fails to install due to a upper case typo. Fixed that and tested that it builds correctly.

drozer: Fixed typo in PKGBUILD.

---

packages/python2-prettytable/PKGBUILD

Reference to @noraj issue. https://github.com/BlackArch/blackarch/issues/2694
```
▲ /tmp/pretty sudo pacman -U python2-prettytable-0.7.2-12-any.pkg.tar.xz
loading packages...
resolving dependencies...
looking for conflicting packages...
Packages (1) python2-prettytable-0.7.2-12
Total Installed Size:  0.15 MiB
:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                    [###############################################] 100%
(1/1) checking package integrity                                                  [###############################################] 100%
(1/1) loading package files                                                       [###############################################] 100%
(1/1) checking for file conflicts …
```

Fix Python Prettytable read permission for CME

---

lists/to-release
packages/dfir_ntfs/PKGBUILD

```
Package dfir_ntfs-1.0.3-1-any.pkg.tar.zst installed correctly! Testing it now...
Extract information from NTFS metadata files, volumes, and shadow copies
Usage:
ntfs_parser --mft <input file ($MFT)> <output file (CSV)>
ntfs_parser --usn <input file ($MFT)> <input file ($UsnJrnl:$J)> <output file (CSV)>
ntfs_parser --log <input file ($MFT)> <input file ($LogFile)> <output file (TXT)>
ntfs_parser --indx <input file (raw image)> <volume offset (in bytes)> <output file (CSV)>
ntfs_parser --all-mft <input file (raw image)> <volume offset (in bytes)> <output file (CSV)>
ntfs_parser --mem <input file (raw memory image)> <output file (CSV)>
```

Add dfir_ntfs to release

---

packages/mobsf/PKGBUILD

Currently when installing mobsf on a clean install of blackarch, I receive a handful of times.
```
ModuleNotFoundError: No module named 'distro'
```
This should prevent that.

Add python-distro as a dependency for mobsf

---

lists/to-release
packages/filebuster/PKGBUILD
packages/perl-future/PKGBUILD
packages/perl-io-async/PKGBUILD
packages/perl-struct-dumb/PKGBUILD
packages/perl-test-identity/PKGBUILD
packages/perl-test-refcount/PKGBUILD

Fix for filebuster https://github.com/BlackArch/blackarch/issues/2759#issuecomment-628388628

Add perl modules for filebuster

---

lists/to-release
packages/ssh-audit/PKGBUILD

- Upgrade to maintained fork: from [arthepsy/ssh-audit](https://github.com/arthepsy/ssh-audit) (x-2016) to [jtesta/ssh-audit](https://github.com/jtesta/ssh-audit) (2010-2020) (fix https://github.com/BlackArch/blackarch/issues/2802)
- upgrade python 2 -> 3
- manual -> `python setup.py`
- upgrade pkgver with git tag (idk if force epoch is required @noptrix to go from `165.22b671e` to `v2.2.0.r0.ge447c42`)
Proof of test:
```
$ ba-dev -e 'ssh-audit' -p ssh-audit-1:v2.2.0.r0.ge447c42-1-any.pkg.tar.zst
...
Package ssh-audit-1:v2.2.0.r0.ge447c42-1-any.pkg.tar.zst installed correctly! Testing it now...
usage: ssh-audit [-1246pbcnjvlt] <host>
-h,  --help             print this help
-1,  --ssh1             force ssh version 1 only
-2,  --ssh2             force ssh version 2 only
-4,  --ipv4 …
```

ssh audit revamp

---

lists/to-release
packages/scoutsuite/PKGBUILD

Scoutesuite by default writes files in your current directory. As this package cd's to the package directory, it returns a permission error as well as not writing to the expected directory. I have removed the cd and referenced the correct directory in both the source and the python execution

Fix change directory error

---

packages/burpsuite/PKGBUILD

Update Burpsuite to 2020.9.1

---

lists/python2-tools
lists/to-release
packages/svn-extractor/PKGBUILD

[Sent a PR to svn-extractor](https://github.com/anantshri/svn-extractor/pull/18) last night to migrate it to Python3. The package is now Python3 (:partying_face: ) and this PR updates it.

svn-extractor: Migrate to py3

---

packages/grype/PKGBUILD

And a bit more:
* #2926 is addressed
* versions are converted to github releases (from commit number)
* `epoch` is introduced to allow updates
* go build flags & options

grype: version bump.

---

lists/to-release
packages/nbtscan/PKGBUILD

Please review; if we need to change pkgname to nbtscan-git please let me know. This package is compiling from src and seams to be running as exepcted.. Changelog included.

nbtscan #2901; pkgbuild src install

---

mirror/mirror.lst

We have recently set up SJTUG mirror for blackarch.
Here is some basic information about our mirror.
```
Country: China
Organization or Name: Shanghai Jiao Tong University Linux User Group (SJTUG)
Contact Name: SJTUG
Contact Email: sjtug-mirror-maintainers@googlegroups.com
Mirror URLs: https://mirror.sjtu.edu.cn/blackarch/
Bandwidth: 1Gbps
Supports IPv6: Yes
```
Maybe we need also update https://blackarch.org/downloads.html#mirror-list

mirror.lst: add SJTUG mirror

---

mirror/mirror.lst

Our organization has been started to mirror BlackArch.
So I would like to request you to add our mirror.
- Additional Information -
Name : krmir FTP (Operated by krmir NPO)
Location : Ulsan, Republic of Korea(South Korea)
Bandwidth : 500Mbps(Main) + 1Gbps(Spare)
Supporting protocol : HTTPS(https://mirror.krmir.org/blackarch), FTP(ftp://mirror.krmir.org/blackarch), RSYNC(rsync://mirror.krmir.org/blackarch)
Source : rsync://blackarch.org/blackarch
Contact : krmir.ftp@gmail.com

Update mirror.lst - add mirror

---

packages/blackarch-keyring/PKGBUILD
packages/blackarch-keyring/blackarch-key.hook

blackarch-keyring: Added pacman hook
Installs blackarch-key.hook into /etc/pacman.d/hooks so that the keys in
blackarch-keyring gets reinstated whenever archlinux-keyring is updated.
This should be a different commit compared to the mistakes that were
done in the past. Changes to remove unnecessary braces were implemented,
the changes are done on a separate branch, and here's hoping all should
work.

blackarch-keyring: Added pacman hook

---

packages/chipsec/Makefile.patch
packages/chipsec/PKGBUILD

Makefile.patch: Fixed multiple issues with half-patched file that was in
my origin/work directory.
PKGBUILD: Bumped pkgrel, updated sha512sums, added changes as mentioned
below.
First and foremost, sorry for pushing a half-baked solution in previous
commit. I have addressed the Makefile.patch as well as updated the
PKGBUILD with new hashsums and changes as per suggestions in the
[commit](https://github.com/BlackArch/blackarch/commit/d3fe35ee50083368db528acb5f7c0850489bed5e).
Full build, install and compile output:
```
$ makepkg -sfC
==> Making package: chipsec 1070.7966175-3 (Mon 08 Feb 2021 20:50:18)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
-> Updating chipsec git repo...
Fetching origin
-> Found Makefile.patch
==> Validating …
```

chipsec: Updated fixes in light of previous commit

---

packages/chipsec/1095-kernel-5.10.patch
packages/chipsec/PKGBUILD

1095-kernel-5.10.patch: File added,
[source](https://github.com/chipsec/chipsec/pull/1095/files)
and was referenced [here](https://github.com/chipsec/chipsec/issues/1086)
PKGBUILD:
* Added the 'epoch=' variable back as per Black Arch upstream.
* Added the patch file which fixes the issue along with checksum.
* Slight rework on 'package() {}' to apply new patches first, before
Makefile.patch.
```
$ makepkg -si
==> Making package: chipsec 4:1070.7966175-3 (Thu 18 Feb 2021 02:27:12)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
-> Cloning chipsec git repo...
Cloning into bare repository '/home/blackarch/blackarch/packages/chipsec/chipsec'...
remote: Enumerating objects: 84, done.
remote: Counting objects: 100% (84/84), done.
remote: …
```

chipsec: Included fix from upstream for 5.10

---

lists/to-release
packages/blackarch-menus/PKGBUILD

We should add blackarch-menus to the blackarch group.
Currently if people run `pacman -S blackarch` it will not be installed
People get confused as the menu structure isn't showing up in desktop Environments that use `.desktop` files as it may be the case in #3055

blackarch-menus: add to blackarch group

---

packages/pwncat/PKGBUILD

Updating pwncat from version 0.1.0 to version 0.1.1
Created as follows:
```bash
#!/usr/bin/env bash
set -e
set -u
set -o pipefail
VERSION="0.1.1"
SHA512="$( curl -sS --fail -L \
"https://github.com/cytopia/pwncat/archive/v${VERSION}.tar.gz" --output - \
| sha512sum \
| awk '{print $1}' \
)"
cat <<- EOF
pkgname=pwncat
pkgver=${VERSION}
pkgrel=1
groups=('blackarch' 'blackarch-backdoor' 'blackarch-scanner' 'blackarch-proxy'
'blackarch-networking')
pkgdesc='Bind and reverse shell handler with FW/IDS/IPS evasion, self-inject and port-scanning.'
url='http://pwncat.org/'
license=('MIT')
arch=('any')
depends=('python')
source=("\$pkgname-\$pkgver.tar.gz::https://github.com/cytopia/\$pkgname/archive/v\$pkgver.tar.gz")
sha512sums=('${SHA512}')
package() {
cd "\$pkgname-\$pkgver"
install -Dm 755 …
```

pwncat 0.1.1 (update 0.1.0 -> 0.1.1)

---

lists/to-release
packages/social-analyzer/PKGBUILD

close  #3080
Seems it doesn't have a proper setup.py
```
$ ba-dev -e 'social-analyzer --cli --username "johndoe" --metadata --extract --trim' -p social-analyzer-0.21-1-any.pkg.tar.zst                                                                                            ...                                                                                                                                                                                                       
Package social-analyzer-0.21-1-any.pkg.tar.zst installed correctly! Testing it now...                                                                                                                                                        
sh: line 1: social-analyzer: command not found
$ ba-dev -e 'bash' -p …
```

social-analyzer: add package

---

packages/PKGBUILD

note: package "python-coverage" requires "pacman -Syy" to be installed

pyaxmlparser: a new tool + a tool dependency

---

packages/cloudsploit/PKGBUILD

Currently, arguments are not parsed to cloudsploit when run using the script
stored in /usr/bin.
This commit fixes that by parsing each argument that was sent to the script to
cloudsploit

cloudsploit: fix: Allow arguments to be parsed

---

lists/to-release
packages/redress/PKGBUILD

https://github.com/goretk/redress
>The redress software is a tool for analyzing stripped Go binaries compiled with the Go compiler. It extracts data from the binary and uses it to reconstruct symbols and performs analysis.
Redress is useful as a standalone binary, but it can also be executed from within radare2. That's when redress truly shines.
>It will extract all the functions and methods and construct symbol flags for them. It will also extract the types in the binary. It will mark the corresponding `_type` with this flag to make analysis easier. By doing this, it highlights which actual type is being allocated on the heap for easier analysis.

Add redress

---

packages/see-surf/PKGBUILD

See-SURF: initial commit

---

packages/proxmark3/PKGBUILD

closes #3191.
i had to add `PREFIX=/usr` because without it the installation process will raise an `permission denied` error while copying binaries.

proxmark3 : initial commit

---

packages/rustcat/PKGBUILD

Changed from rc to rcat to prevent clash with /sbin/rc on openrc systems.

rustcat: Update binname

---

packages/gitdump/PKGBUILD

The caller script `cd`'d into the install dir, while `git-dump.py` has its output directory hard coded as `outputFolder = "output/"`. So the output would be written to the install dir. This was bad practice, confusing, and required root to run the tool.

Fix `gitdump` caller script

---

lists/to-release
packages/rmiscout/PKGBUILD

fix #3266
PS: keep `jre8-openjdk-headless` and not `java-environment` because it works properly only under java 1.8

rmiscout: 1st commit

---

packages/nettacker/PKGBUILD

Nettacker is the only package in `blackarch-scanners` group. I think it was supposed to be in `blackarch-scanner` instead.

nettacker: fix typo in group name

---

packages/theharvester/PKGBUILD

python-ujson is a missing dependecie for theharvester

theharvester: added python-ujson

---

packages/automato/automato.install
packages/beef/beef.install
packages/binproxy/binproxy.install
packages/catphish/catphish.install
packages/cewl/cewl.install
packages/ciphr/ciphr.install
packages/cmsscanner/cmsscanner.install
packages/cve-api/cve-api.install
packages/dawnscanner/dawnscanner.install
packages/fingerprinter/fingerprinter.install
packages/hoper/hoper.install
packages/joomlavs/joomlavs.install
packages/kautilya/kautilya.install
packages/sitediff/sitediff.install
packages/smbexec/smbexec.install
packages/ssrf-proxy/ssrf-proxy.install
packages/tlspretense/tlspretense.install
packages/twofi/twofi.install
packages/vsaudit/vsaudit.install
packages/whatweb/whatweb.install
packages/whitewidow/whitewidow.install
packages/wordpress-exploit-framework/wordpress-exploit-framework.install
packages/wpbrute-rpc/wpbrute-rpc.install
packages/xspear/xspear.install
packages/yasuo/yasuo.install

no need to pkgrel++ and release, it can wait next update, it's just to remove teh deprecated flag and avoid the warning

bundle: remove deprecated path option

---

packages/responder/PKGBUILD

Fix this:
```
$ sudo responder --help                                                                                                                                                                                                                     
You need to install python-netifaces or run Responder with python3...                                                                                                                                                                       
Try "apt-get install python-netifaces" or "pip install netifaces"
```
Workaround: `sudo pacman -S python-netifaces --asdeps`

responder: fix deps

---

packages/bloodhound/PKGBUILD

- fix upload data issue by passing from 4.0.3 to 4.1.0
- neo4j 4.x requires Java 11 rather than 8 (cf. https://neo4j.com/docs/operations-manual/current/installation/requirements/#deployment-requirements-java)
- use neo4j service
TODO :
add `/etc/systemd/system/neo4j.service.d/override.conf`
```ini
[Service]
Environment=JAVA_HOME=/usr/lib/jvm/java-11-openjdk
```

bloodhound: multi-fix

---

packages/autorecon/PKGBUILD

By default autorecon outputs to ./results, which we expect to be the current directory

autorecon: Fixes current PATH

---

packages/ikeforce/PKGBUILD

Fix this issue:
```
$ ikeforce 10.0.0.1
/usr/lib/python2.7/site-packages/OpenSSL/crypto.py:14: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
from cryptography import utils, x509
Traceback (most recent call last):
File "ikeforce.py", line 13, in <module>
import ikehandler
File "/usr/share/ikeforce/ikehandler.py", line 10, in <module>
import ikecrypto
File "/usr/share/ikeforce/ikecrypto.py", line 13, in <module>
from Crypto.Cipher import *
ImportError: No module named Crypto.Cipher
```

ikeforce: fix deps

---

packages/lfimap/PKGBUILD

Hi there!
I changed the source for lfimap to something correct (python3 + more features added).
The new source repo is located here: https://github.com/hansmach1ne/lfimap
**It requires python-pybase64 as dep. This is why I created the PKGBUILD for the lib before ;)**
Hope it's ok!
Cheers!

lfimap: update source.

---

lists/to-release
packages/airgeddon/PKGBUILD

also remove binutils makedepends since it's base-devel

airgeddon: version bump

---

packages/neo-regeorg/PKGBUILD

- pkgver: use git tag (no need for epoc)
- GPL3 is in licenses package cf. https://wiki.archlinux.org/title/PKGBUILD#license

neo-regeorg: enhance packaging

---

packages/responder/PKGBUILD

- pkgver: use git tag
- GPL3 is in licenses package cf. https://wiki.archlinux.org/title/PKGBUILD#license

responder: enhanced packaging

---

packages/angrop/PKGBUILD

upstream changed from setuptools to PEP517 https://github.com/angr/angrop/commit/928ed1ec52d7aa53022d6c07591a60594298789a
I have added it to https://github.com/BlackArch/blackarch-pkgbuilds/commit/4ae2d3f269ad76eda2d78f3ea172e9bba6fd1835
Thank @ph20 for the work with python-build

angrop: fix building

---

packages/avaloniailspy/PKGBUILD

no need for epoch or pkgrel++
```
irb(main):001:0> ['216.113ef11','v7.2.rc.r0.g113ef11'].sort
=> ["216.113ef11", "v7.2.rc.r0.g113ef11"]
```

avaloniailspy: better pkgver

---

packages/avml/PKGBUILD

no need for epoch or pkgrel++
```
irb(main):001:0> ['93.155f084','v0.6.1.r11.g155f084'].sort
=> ["93.155f084", "v0.6.1.r11.g155f084"]
```

avml: better pkgver

---

lists/to-release
packages/dependency-check/PKGBUILD

This was wrongly creating an `defensive,`category. Replace https://github.com/BlackArch/blackarch-site/pull/151/files. It's better to fix the source.
https://github.com/BlackArch/blackarch-site/pull/151/files

dependency-check: fix groups

---

packages/ivre/PKGBUILD

This PR:
* (updates the current dev version)
* removes the unneeded dependency to python2-setuptools (Python 2 is no longer supported by IVRE)
* updates the repository URL (the project has moved from cea-sec org to its own org; the redirection works but it's better to use the correct URL anyway)
* adds a `-blackarch-1` to the internal version number (makes debugging easier)

IVRE: update source repos, remove unused dep

---

packages/whispers/PKGBUILD

Hey there, I am the creator of whispers. I saw that awesomely it was included into BlackArch, and I thought I would contribute by updating it to the latest version. [Ownership changed](https://github.com/adeptex/whispers/blob/2.0.6/RELEASE_NOTES.md#dizzy-licensing-changes-dizzy) from Skyscanner to my personal account. In addition, Skyscanner's [version 1](https://github.com/Skyscanner/whispers/) is no longer maintained.
Let me know if you need any additional details. Thanks!

Update whispers to 2.1.0

---

packages/spiderpig-pdffuzzer/PKGBUILD

The link in the source is not working when executing a ``makepkg`` command.

spiderpig-pdffuzzer: Update PKGBUILD

---

packages/neo-regeorg/PKGBUILD

Move the main script file since it would locate the template file depending on where it's located.
This pull request closes #3503

neo-regeorg: move the main script file to its dir

---

packages/jwt-tool/PKGBUILD

When `-M cc` option is used, fails with `FileNotFoundError: [Errno 2] No such file or directory: 'common-headers.txt'` error while the file is in `/usr/share/jwt-tool/common-headers.txt`.

jwt-tool: fix wrapper

---

packages/brakeman/PKGBUILD

When I run `brakeman relative/path/source`, brakeman is looking into `brakeman_install_dir + user_provided_path` (`/opt/brakeman/relative/path/source`) instead of `shell_current_path + user_provided_path` (`~/project/example/relative/path/source`).
```
$ brakeman relative/path/source
Loading scanner...
Please supply the path to a Rails application (looking in /opt/brakeman/relative/path/source).
Use `--force` to run a scan anyway.
```
Which is due to the `/usr/bin/brakeman` wrapper which do a cd in `/opt/brakeman` but the tool seems to run just fine with a direct `exec`.
So this will avoid to have to do `brakeman "$pwd/relative/path/source"`.

brakeman: better package

---

.github/workflows/tests.yml

actions/checkout@v2 needs to be updated to v3 to fix deprecation warning as can be seen [here](https://github.com/BlackArch/blackarch/actions/runs/3505267291):
```
Node.js 12 actions are deprecated. For more information
see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Please update the following actions to use Node.js 16: actions/checkout@v2
```
The ubuntu version is fixed to avoid future issues if ubuntu 22.04 gets used as latest, where python 2.7 might not be available by default

Actions: Bump Action versions and fix ubuntu version

---

packages/evil-winrm/PKGBUILD

- remove the tmp fix in prepare() since ruby-rexml has been added in depends()
- add git as runtim dep. and copy .git folder because git is used in gemspec so we need it for bundle exec
- fix #3593 (partially)

evil-winrm: build fixes

---

packages/x8/PKGBUILD

- fix dependencies
- add openssl that was missing
- add openssl-1.1 as tmp fix for https://github.com/Sh1Yo/x8/issues/26#issuecomment-1325795207
- update pkgver (commit 135 -> 255)
- fix #3592

x8: fix and update

---

mirror/mirror.lst

**Mirror domain name:**
md.mirrors.hacktegic.com
**Geographical location of the mirror (country):**
Moldova
**URLs for supported access methods (http(s), rsync) (no ftp):**
http://md.mirrors.hacktegic.com/blackarch/
https://md.mirrors.hacktegic.com/blackarch/
**Your mirror's available bandwidth:**
1Gbit, server is at IX "KIVIX" - Chisinau Internet Exchange
**An administrative contact email:**
[amocrenco@protonmail.com](mailto:amocrenco@protonmail.com)
**An alternative administrative contact email:**
[artiomm@hacktegic.com](mailto:artiomm@hacktegic.com)
**Syncing from:**
rsync://mirrors.dotsrc.org/blackarch/ every 2 hours at random minute

New Mirror in Moldova: md.mirrors.hacktegic.com

---

packages/ida-free/PKGBUILD

PKGBUILD from https://aur.archlinux.org/packages/ida-free with fix to errors during the building.
IDA is a light but powerful tool can quickly analyze the binary code samples and users can save and look closer at the analysis results.

ida-free: add package

---

packages/networkminer/networkminer.desktop

Deleted `MimeType=application/x-executable` because it forces AppImage files to open NetworkMiner when the AppImage has in Properties "Executable as a Program" disabled and when the user double click on AppImage file itself.

Deleted MimeType=application/x-executable

---

packages/bloodhound/PKGBUILD

Proposal of change for avoiding the pkg conflicts. Bloodhound with nodejs has been tested and working correctly.

bloodhound - Switched dep from nodejs-lts-gallium to nodejs

---

lists/broken
lists/to-release
packages/manticore/PKGBUILD
packages/python-wasm/PKGBUILD
packages/python-z3-solver-pep517/PKGBUILD

- fix pkgver
- updates dependencies (add new like python-wasm ones and remove uneeded like python-pygoogle)
- deprecate python-pygoogle because it's broken and manticore was the only package using it
- add a pep517 built version of python-z3-solver to workaround https://github.com/trailofbits/manticore/issues/1426
- manticore will still be broken because of requiring protobuf~=3.20 cf. https://github.com/trailofbits/manticore/issues/2559
fixes #3681
replaces #3682

manticore: fix dependencies

---

lists/to-release
packages/python-python-wappalyzer/PKGBUILD

add missing dependencies cf. https://github.com/chorsley/python-Wappalyzer/blob/cc2198377bf1e548f43e64815b1a135152d3a549/setup.py#L22-L26
replaces #3672

fix python-python-wappalyzer

---

packages/python-aiosmtplib/PKGBUILD

Used for LinkScope tool to avoid the usage of Python venv: https://github.com/BlackArch/blackarch/issues/3659

python-aiosmtplib: added package

---

packages/python-social-analyzer/PKGBUILD

Used for LinkScope tool to avoid the usage of Python venv: https://github.com/BlackArch/blackarch/issues/3659

python-social-analyzer: added package

---

packages/python-name-that-hash/PKGBUILD

Used for LinkScope tool to avoid the usage of Python venv: https://github.com/BlackArch/blackarch/issues/3659

python-name-that-hash: added package

---

lists/to-release
packages/sherlock/PKGBUILD

The current Sherlock in BlackArch uses `username_unclaimed` attribute so, when it is used, you will receive an error. This issue is solved on the latest version of Sherlock.

sherlock: version bump

---

packages/android-apktool/PKGBUILD

- the build was failing so the binary version available was not 2.6.0 but 2.5.0, we have to fix java 17 as Gradle does not support java 19 yet
- bump to 2.7.0

apktool: pkgver bump + fix build

---

lists/to-release
packages/kerberoast/PKGBUILD

It solves the conflict issues due to the usage of `tests` folder in the root of Python3.10 folder. It has been solved on https://github.com/skelsec/kerberoast/pull/9

kerberoast: version bump

---

lists/to-release
packages/scamper/PKGBUILD

scamper updated and removed `linux-headers` dependency because no needed.

scamper: version bump

---

lists/to-release
packages/pcileech/PKGBUILD

According to the project page, there is no request about the usage of `linux-headers` package. The install of this package could be dangerous for those systems using different kernel types. it could break the system.
The needed dependencies for pcileech are specified at https://github.com/ufrisk/pcileech/wiki/PCILeech-on-Linux

pcileech: moved linux-headers dependency to optdepends

---

lists/to-release
packages/python-zconfig/PKGBUILD

It is a dependency of `pwncat-caleb` tool. Currently, `pwncat-caleb` cannot be installed because this dependency is missing from repository.

python-zconfig: add package

---

lists/to-release
packages/python-idna_ssl

python-idna_ssl has been removed from Arch community repository and it is a dependency of some BlackArch tools.

python-idna_ssl: add package

---

lists/to-release
packages/python-pip-shims/PKGBUILD

python-pip-shims has been removed from Arch repository and moved to AUR and it is used as dependency for some BlackArch tool.

python-pip-shims: add package

---

lists/to-release
packages/python-pysctp/PKGBUILD

According to the project page, there is no request about the usage of `linux-headers` package. The install of this package could be dangerous for those systems using different kernel types. it could break the system.
The needed dependencies for pysctp are specified at https://github.com/P1sec/pysctp/blob/master/README.txt or https://github.com/P1sec/pysctp/blob/master/Makefile in `installdeps` rule.
Furthermore, python2 logic removed because deprecated and security risk.

python-pysctp: moved linux-headers dependency to optdepends

---

lists/to-release
packages/python-pysctp/PKGBUILD

On the previous PR https://github.com/BlackArch/blackarch/pull/3753 I forgot to remove linux-headers from the package() functions since they have been already specified in optdepends at the beginning.

python-pysctp: fixed linux-headers in package()

---

lists/to-release
packages/calamares/PKGBUILD

I tried to force install the [ALCI calamares package](https://github.com/arch-linux-calamares-installer/alci_repo/blob/master/x86_64/alci-calamares-3.3.0.230321-04-x86_64.pkg.tar.zst), which works with our configs on the slim iso (at least the interface, haven't tried to install the iso so far). 
I tried to make our PKGBUILD match [their's](https://github.com/arch-linux-calamares-installer/alci-pkgbuild/blob/master/calamares/alci-calamares/calamares-3.3.0.230321-04/PKGBUILD). Can someone please try to verify this? The package builds, but I get an issue with not matching QT versions and running out of time for now.

calamares: update PKGBUILD

---

packages/python-dsinternals/PKGBUILD

Still using python 3.10 instead of 3.11

python-dsinternals py11

---

packages/bqm/PKGBUILD

- no need to hardcode _gemver and to append it to /usr/lib/ruby/gems/ because that's actually what _gemdir is
- the official name of gemdir is gemhome
- ruby -e'puts Gem.default_dir can be replaced by the much simpler and elegant gem env home

bqm: enhance packaging

---

lists/to-release
packages/empire/PKGBUILD
packages/python-secretsocks/PKGBUILD

The command `empire-server` needs of PySecretSOCKS lib for working. The produced error is:
```
ModuleNotFoundError: No module named 'secretsocks'
```
It can be fixed by installing `python-secretsocks` that is added on BlackArch by this PR.

empire: add python-secretsocks dependency

---

lists/to-release
packages/python-tls-parser/PKGBUILD
packages/sslyze/PKGBUILD

python-tls-parser:
-  hasn't been build for python 3.11 which made sslyze fail. 
- remove python2 instructions as no package in our repo is using it
sslyze:
- was missing a dependency (python-pyopenssl).
change both packages to PEP517

sslyze: Fix sslyze and dependency

---

lists/to-release
packages/recoverdm/PKGBUILD

This tool is old but it uses simple libraries and it still works. It is used on new Kali Purple as purple team tool.
Feel free to add it or not.
I closed by mistake the previous PR: https://github.com/BlackArch/blackarch/pull/3821

added: recoverdm

---

packages/python-exchangelib/PKGBUILD
packages/python-requests-ntlm/PKGBUILD
packages/python-requests-oauthlib/PKGBUILD
packages/trevorproxy/PKGBUILD
packages/trevorspray/PKGBUILD

- Add multiple dependencies
- trevorproxy
- python-exchangelib
- python-requests-oauthlib
- python-requests-ntlm
- move trevorspray from git to release version
- move from venv to pypi
- use PEP517

Fix trevorspray

---

packages/crackmapexec-poetry/PKGBUILD
packages/crackmapexec-poetry/crackmapexec-poetry.install

as crackmapexec is a dependency nightmare and it's nearly impossible to maintain a package for it without system dependency issue, I suggest an alternative package using a virtual environment with poetry

crackmapexec-poetry: add package

---

packages/tor-browser/PKGBUILD
packages/tor-browser/tor-browser.desktop
packages/tor-browser/tor-browser.install

Fixes the following error:
`
/usr/bin/tor-browser: Your version in /home/markustieger/.tor-browser is outdated or you do not have installed tor-browser yet.
/usr/bin/tor-browser: Extracting files to /home/markustieger/.tor-browser/INSTALL.
tar (child): /opt/tor-browser/tor-browser-linux64-12.5.4_en-US.tar.xz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
`
It trys to extract the /opt/tor-browser/tor-browser-linux64-12.5.4_en-US.tar.xz file, but it's called /opt/tor-browser/tor-browser-linux64-12.5.4_ALL.tar.xz. This is the fix

Fixed Tor-Browser package

---

lists/to-release
packages/cerbeyra-api/PKGBUILD

This library provides a high level interface for interacting with Cerbeyra’s APIs and retrieving cyber-threat’s information from them. Through such API’s, it is possible to get clues regarding vulnerability assessments, cyber feeds, governance, threat intelligence and much more.
Just not sure about the `python-setuptools` dependency specified in its `pyproject.toml` file. This dependency could be still needed to build the package even if it is not based on setup.py?

add python-cerbeyra-api

---

packages/netexec/PKGBUILD
packages/netexec/netexec.install

fix #3948
NetExec is the community fork of CrackMapExec and where the project continue to live on. Porchetta Industries is dead and has been removed.
Prochetta repo was moved back to byt3bl33d3r that is inactive and will probably be abandoned.
So:
- https://github.com/Porchetta-Industries/CrackMapExec 🔴 dead, removed
- https://github.com/mpgn/CrackMapExec 🔴 dead, removed
- https://github.com/byt3bl33d3r/CrackMapExec 🟡 inactive, soon be abandoned, tag 6.0 and 6.1 is missing (but commits are present)
- https://github.com/Pennyw0rth/NetExec 🟢 active, community devs
For now, we can keep crackmapexec package is case but I provided the netexec package as well, there should be not conflict as all binaries and code were renamed:
- crackmapexec ➡️ netexec
- cme ➡️ nxc
- cmedb ➡️ nxcdb

netexec: release

---

packages/stegdetect/0001-tree-wide-rename-progname-to-avoid-conflicts.patch
packages/stegdetect/PKGBUILD
packages/stegdetect/rules.ini

Fixes #3965.
---
Edit: I've reformatted the patch. Looks like my editor is automatically formatting C source files without asking 🙄🙄🙄

stegdetect: add default `stegbreak` rules and fix FTBFS

---

lists/to-release
packages/modifycerttemplate/PKGBUILD

[modifyCertTemplate](https://github.com/fortalice/modifyCertTemplate) is designed to aid an operator in modifying ADCS certificate templates so that a created vulnerable state can be leveraged for privilege escalation (and then reset the template to its previous state afterwards).

modifycerttemplate: add package

---

lists/to-release
packages/unix-privesc-check/PKGBUILD

Fixed sha512 and binary name that was wrongly `unix-privsc-check`.

fixed unix-privesc-check

---

lists/to-release
packages/exe2hexbat/PKGBUILD

Convert a Windows PE executable file to a batch file and vice versa. Ref:  https://www.kali.org/tools/exe2hexbat/
https://github.com/g0tmi1k/exe2hex/

add exe2hex

---

packages/wfuzz/PKGBUILD

I tried to install wfuzz from a fresh blackarch on Arch Linux and got a "QuotedString" NameError exception.
A `sudo pacman -S python-pyparsing` solved the issue which is why I propose to include it in the deps of the package

python-pyparsing dependency needed to provide QuotedString

---

packages/yaaf/PKGBUILD

- github username was renamed so it's redirecting to a new namespace
- fix bad upstream packaging resulting in conflicts cf. #3996

yaaf: fix deployment

---

lists/to-release
packages/perl-data-validate-ip/PKGBUILD

Dependency no longer on Arch Linux repos and breaking `witchxtool`.

Adding missing perl-data-validate-ip dependency for witchxtool

---

packages/tor-browser/PKGBUILD

Fixes that the arch variable doesn't get replaced in "tor-browser.in".
and btw simple question:
Do you even test this package? It's the second time, something broke.
(it hasn't found the tar.xz file, because the $PACKAGE_ARCH" was not replaced and because of that, it tryed to extract from a filepath, that does not exist)

Fixed Tor-Browser package (again)

---

packages/smbmap/PKGBUILD

- update to 1.10.2 https://github.com/ShawnDEvans/smbmap/tags
- add missing dependency https://github.com/ShawnDEvans/smbmap/blob/dc3f98aad9db709d609dc3e07428e29746fe6946/setup.py#L30
- move `pkgver()` to tags (no need for epoch https://semvercompare.azurewebsites.net/?version=166.73c9907&version=v1.10.2.r0.gdc3f98a)

smbmap: various upgrade

---

packages/retdec/PKGBUILD

Avoid retdec-decompiler symlink overwriting the retdec-decompiler binary, add dependency for source compilation and clean empty symlinks.

Fix retdec PKGBUILD

---

mirror/mirror.lst

Due to infrastructure changes, the URL changed from mirror.surf to repository.su.
New url:
https://repository.su/blackarch
http://repository.su/blackarch
rsync://repository.su/blackarch

Change mirror url

---

packages/smap-scanner/PKGBUILD

There is another tool with the same name but it's a different one.
```
➜ pacman -Si smap | grep Description
Description     : Shellcode mapper - Handy tool for shellcode analysis.
```
closes #4035

add smap-scanner

---

packages/semgrep/PKGBUILD

auto-update was prevented by the tmp fix causing error as the binary wasn't there anymore
it has been handled upstream (see https://github.com/semgrep/semgrep/issues/9571) so the fix is no longer required.

semgrep: update and fix build

---

packages/airgeddon/PKGBUILD

I know git package should be auto-bumped but as this one was not for 5 months I guess it's missing from the batch.

airgeddon bump

---

packages/apkleaks/PKGBUILD

it requirs jadx at runtime to decompile

apkleaks: add missing dependency

---

packages/impacket-ba/PKGBUILD

- AL package has not been updated since 2023-06-01 while no other packages depends on it.
- AL package is regularly out of date for a long time
- Some scripts are suffering some bugs that have been corrected in newer version, e.g. https://gitlab.archlinux.org/archlinux/packaging/packages/impacket/-/issues/1
- AL package is missing several dependencies required at runtime that are also declared upstream, see. https://gitlab.archlinux.org/archlinux/packaging/packages/impacket/-/issues/2
For all those reasons, I decided to provide our own package that will better reflects our standards and be updated more frequently. I added the `provides` and `conflicts` so we can choose from one or another in other package dependencies.

add impacket-ba

---

mirror/mirror.lst

Hi, we host a new mirror in China and want to add it to official mirror list. 
Email: mirror_support@hust.edu.cn
Alternative email: tttturtleruss@hust.edu.cn

Add a new mirror in China

---

lists/to-release
packages/evil-winrm/PKGBUILD

I added an extra environment variable to avoid changing directory when executing, because this causes issues with stuff like the download and upload function of the program.

evil-winrm: Set environment variable instead of changing directory

---

lists/to-release
packages/eaphammer/PKGBUILD

https://github.com/BlackArch/blackarch/issues/4182
Added Python 3.12 support.

eaphammer: fix dependencies

---

packages/xray/PKGBUILD
packages/xsss/PKGBUILD
packages/xxeserv/PKGBUILD

go.mod already existed, so build() errored out.

fix xxeserv build

---

lists/to-release
packages/cubicsdr/PKGBUILD

It needs at least one SOAPy package to be installed to work. Evaluate if move the related packages from optional to mandatory.
At start, the executable produces not-blocking messages like:
```
/usr/src/debug/wxwidgets/wxWidgets/src/unix/glegl.cpp(386): assert ""Assert failure"" failed in InitVisual(): Failed to get an EGLConfig for the requested attributes.
```
Reported on [AUR](https://aur.archlinux.org/packages/cubicsdr#comment-993142) and [upstream](https://github.com/cjcliffe/CubicSDR/issues/1037).

cubicsdr: add package

---

lists/to-release
packages/qt5-webkit/PKGBUILD
packages/qt5-webkit/qt5-webkit-icu75.patch

Fix https://github.com/BlackArch/blackarch/issues/4165
After merging this update, I think that [wkhtmltopdf](https://github.com/BlackArch/blackarch/blob/master/packages/wkhtmltopdf/PKGBUILD) needs to be rebuilt in order to refer to the new libraries.

qt5-webkit: version bump

---

lists/to-release
packages/regripper/PKGBUILD

The latest commit solves the issue related to the not found plugins directory when a binary wrapper is used.
Close https://github.com/BlackArch/blackarch/issues/4314

regripper: bump version

---

packages/python-alive-progress/PKGBUILD

Version 3.2.0 was released of this
https://pypi.org/project/alive-progress/
Changed install to conform to PEP 517
https://wiki.archlinux.org/title/Python_package_guidelines#Standards_based_(PEP_517)
This resolves Issue https://github.com/BlackArch/blackarch/issues/4333

python-alive-progress: bump version

---

lists/to-release
packages/pkgcheck-arch/PKGBUILD

Added support for Python 3.12, fixed typos and added check on base-devel dependencies.
Close https://github.com/BlackArch/blackarch/issues/3391

pkgcheck-arch: bump version

---

lists/to-release
packages/vmcloak/PKGBUILD
packages/vmcloak/setup.py.patch

Close https://github.com/BlackArch/blackarch/issues/2980
For the usage, refer to:
https://github.com/Cryss76/vmcloak/blob/main/docs/qemu.rst
https://github.com/Cryss76/vmcloak/blob/main/docs/vmcreation.rst

vmcloak: migration to Python3 and fix issues

---

lists/to-release
packages/sdrsharp/PKGBUILD
packages/sdrsharp/adsbspy.desktop
packages/sdrsharp/airspycalibrate.desktop
packages/sdrsharp/astrospy.desktop
packages/sdrsharp/sdrsharp.desktop
packages/sdrsharp/sdrsharp_wrapper
packages/sdrsharp/spectrumspy.desktop

Close https://github.com/BlackArch/blackarch/issues/3789

sdrsharp: add package

---

lists/to-release
packages/valhalla-api/PKGBUILD

Close https://github.com/BlackArch/blackarch/issues/4209
I'm not sure if it is the right process. The `valhalla` package should be removed from the main mirror repo.

valhalla: rename to valhalla-api

---

packages/simple-lan-scan3/PKGBUILD

Ported the python2-written blackarch tool simple-lan-scan to a python3 version

Port of python2 blackarch tool simple-lan-scan to a python3 version

---

lists/to-release
packages/bruno/PKGBUILD
packages/bruno/com.usebruno.app.Bruno.desktop
packages/nvm/PKGBUILD
packages/nvm/init-nvm.sh
packages/nvm/install-nvm-exec
packages/nvm/nvm.install

Close https://github.com/BlackArch/blackarch/issues/4097

bruno: add package

---

lists/to-release
packages/roadtools/PKGBUILD

Close https://github.com/BlackArch/blackarch/pull/2940/files and https://github.com/BlackArch/blackarch/issues/2885

roadtools: add package

---

packages/semgrep/PKGBUILD
packages/semgrep/semgrep.install

- no more dependencies back and forth
- it's a binary package anyway, it's not possible to build from source
- that's will greatly facilitate maintenance
fix #4392

semgrep: move to standalone package

---

lists/to-release
packages/dnswatch/PKGBUILD
packages/dnswatch/dnswatch.install

Close https://github.com/BlackArch/blackarch/issues/4003

dnswatch: add package

---

lists/to-release
packages/remote-method-guesser/PKGBUILD

Close https://github.com/BlackArch/blackarch/issues/4433
PKGBUILD includes ysoserial and bash completion support.

remote-method-guesser: add package

---

packages/pyinstaller/PKGBUILD
packages/pyinstaller/fortify-source-fix.patch

pyinstaller: update and fix to v6

---

packages/bloodhound/PKGBUILD
packages/neo4j-community/PKGBUILD

- bloodhound: no pkgrel++ because there is no need to redistribute for that change
- neo4j: I got mvn package process killed during building (similar to https://stackoverflow.com/questions/19254735/maven-build-process-gets-killed-when-compiling-gwt) probably because out of memory in my dev VM, so the change is untested

bloodhound & neo4j update

---

lists/to-release
packages/faradaysec/PKGBUILD

Restkit dependency have been dropped from the project since 2018 as reported in the CHANGELOG project file.

faradaysec: remove restkit dependency

---

lists/to-release
packages/bkcrack/PKGBUILD

make build() align with Arch Cmake Package Guidelines
Use doxygen to build doc
Run test
Use SPDX license identifier
optdepends on python for tools
Install example to doc folder
depends on glibc

bkcrack: enhance

---

mirror/mirror.lst

Hello, we have newly added BlackArch and would like to register for the official mirror. The location is South Korea.
Contact email: mirror@mail.daxhub.net

Add South Korean Mirror

---

packages/donpapi/PKGBUILD
packages/python-dploot/PKGBUILD
packages/python-flask-rich/PKGBUILD
packages/python-jwt/PKGBUILD
packages/python-ochre/PKGBUILD
packages/python-stransi/PKGBUILD

fixes #4512
Refactor to upgrade to donpapi v2
https://x.com/_zblurx/status/1809228045435240583
it also brings dploot v3, as it's a dependency of donpapi now
https://x.com/_zblurx/status/1818645383943163938
several new transitive dependencies are introduces that could also be useful for other projects:
- python-flask-rich
- python-jwt
- python-ochre
- python-stransi
- ✅ `ba-dev -I ../python-ochre/python-ochre-0.4.0-1-any.pkg.tar.zst -I ../python-stransi/python-stransi-0.3.0-1-any.pkg.tar.zst -I ../python-flask-rich/python-flask-rich-0.4.1-1-any.pkg.tar.zst -I ../python-dploot/python-dploot-3.1.2-1-any.pkg.tar.zst -I ../python-jwt/python-jwt-1.3.1-1-any.pkg.tar.zst`
- ✅ `ba-dev -e 'donpapi' -p donpapi-1:V1.2.0.r40.g61db37a-1-any.pkg.tar.zst`
- ✅ `sudo pacman -U …

donpapi: upgrade to v2

---

packages/uff/PKGBUILD

Hi there!
Initial commit for [uff](https://github.com/sw33tLie/uff) ("unleashed ffuf") by @sw33tLie.
Hit me up if there's any mistakes!
Cheers!

uff: initial commit.

---

.github/workflows/tests.yml

The runner `ubuntu-20.04` has been deprecated since 2025-04-15, see https://github.com/actions/runner-images/issues/11101

ci: update ubuntu runner version and actions/checkout version

---

COPYING

Remove
```
The list of authors (AUTHORS) must be distributed in its original form with all redistributions of the source code.
```
because no applicable.

Update COPYING - Removing unused AUTHORS sentence

---

lists/to-release
packages/bloodhound/PKGBUILD
packages/bloodhound/bloodhound.install

Remove `alsa-lib gtk3 libxss nss gconf libxtst` dependencies. No references found in the source code (unless I'm drunk).
Close: https://github.com/BlackArch/blackarch/issues/4543

bloodhound: removing unused dependencies

---

mirror/mirror.lst
scripts/check-mirror

Example of output:
```
[+] Checking mirror sync status, please wait...
[IN SYNC]
Berkeley -> http://mirrors.ocf.berkeley.edu/blackarch/lastupdate
Berkeley -> https://mirrors.ocf.berkeley.edu/blackarch/lastupdate
CICKU -> http://au.mirrors.cicku.me/blackarch/lastupdate
CICKU -> http://ca.mirrors.cicku.me/blackarch/lastupdate
CICKU -> http://de.mirrors.cicku.me/blackarch/lastupdate
CICKU -> http://eu.mirrors.cicku.me/blackarch/lastupdate
CICKU -> http://in.mirrors.cicku.me/blackarch/lastupdate
CICKU -> http://jp.mirrors.cicku.me/blackarch/lastupdate
CICKU -> http://kr.mirrors.cicku.me/blackarch/lastupdate
CICKU -> http://mirrors.cicku.me/blackarch/lastupdate
CICKU -> http://sg.mirrors.cicku.me/blackarch/lastupdate
CICKU -> http://us.mirrors.cicku.me/blackarch/lastupdate
CICKU -> …
```

check-mirror: added signature key checks feature
